(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var k;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function p(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},q="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function r(a,b){if(b){var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&q(c,a,{configurable:!0,writable:!0,value:b})}}var ea;
if("function"==typeof Object.setPrototypeOf)ea=Object.setPrototypeOf;else{var fa;a:{var ha={U:!0},ia={};try{ia.__proto__=ha;fa=ia.U;break a}catch(a){}fa=!1}ea=fa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ja=ea;
function ka(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ja)ja(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.C=b.prototype}
r("Promise",function(a){function b(f){this.b=0;this.g=void 0;this.a=[];var h=this.c();try{f(h.resolve,h.reject)}catch(l){h.reject(l)}}function c(){this.a=null}function d(f){return f instanceof b?f:new b(function(h){h(f)})}if(a)return a;c.prototype.b=function(f){if(null==this.a){this.a=[];var h=this;this.c(function(){h.g()})}this.a.push(f)};var e=da.setTimeout;c.prototype.c=function(f){e(f,0)};c.prototype.g=function(){for(;this.a&&this.a.length;){var f=this.a;this.a=[];for(var h=0;h<f.length;++h){var l=
f[h];f[h]=null;try{l()}catch(m){this.f(m)}}}this.a=null};c.prototype.f=function(f){this.c(function(){throw f;})};b.prototype.c=function(){function f(m){return function(n){l||(l=!0,m.call(h,n))}}var h=this,l=!1;return{resolve:f(this.B),reject:f(this.f)}};b.prototype.B=function(f){if(f===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.M(f);else{a:switch(typeof f){case "object":var h=null!=f;break a;case "function":h=!0;break a;default:h=!1}h?this.A(f):this.i(f)}};
b.prototype.A=function(f){var h=void 0;try{h=f.then}catch(l){this.f(l);return}"function"==typeof h?this.T(h,f):this.i(f)};b.prototype.f=function(f){this.j(2,f)};b.prototype.i=function(f){this.j(1,f)};b.prototype.j=function(f,h){if(0!=this.b)throw Error("Cannot settle("+f+", "+h+"): Promise already settled in state"+this.b);this.b=f;this.g=h;this.o()};b.prototype.o=function(){if(null!=this.a){for(var f=0;f<this.a.length;++f)g.b(this.a[f]);this.a=null}};var g=new c;b.prototype.M=function(f){var h=this.c();
f.v(h.resolve,h.reject)};b.prototype.T=function(f,h){var l=this.c();try{f.call(h,l.resolve,l.reject)}catch(m){l.reject(m)}};b.prototype.then=function(f,h){function l(x,E){return"function"==typeof x?function(pa){try{m(x(pa))}catch(qa){n(qa)}}:E}var m,n,u=new b(function(x,E){m=x;n=E});this.v(l(f,m),l(h,n));return u};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.v=function(f,h){function l(){switch(m.b){case 1:f(m.g);break;case 2:h(m.g);break;default:throw Error("Unexpected state: "+
m.b);}}var m=this;null==this.a?g.b(l):this.a.push(l)};b.resolve=d;b.reject=function(f){return new b(function(h,l){l(f)})};b.race=function(f){return new b(function(h,l){for(var m=p(f),n=m.next();!n.done;n=m.next())d(n.value).v(h,l)})};b.all=function(f){var h=p(f),l=h.next();return l.done?d([]):new b(function(m,n){function u(pa){return function(qa){x[pa]=qa;E--;0==E&&m(x)}}var x=[],E=0;do x.push(void 0),E++,d(l.value).v(u(x.length-1),n),l=h.next();while(!l.done)})};return b});
r("Symbol",function(a){function b(e){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(e||"")+"_"+d++,e)}function c(e,g){this.a=e;q(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.a};var d=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&q(d.prototype,a,{configurable:!0,writable:!0,value:function(){return la(aa(this))}})}return a});function la(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function ma(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function na(){this.i=!1;this.f=null;this.o=void 0;this.a=1;this.c=this.g=0;this.j=this.b=null}function oa(a){if(a.i)throw new TypeError("Generator is already running");a.i=!0}k=na.prototype;k.D=function(a){this.o=a};function ra(a,b){a.b={P:b,S:!0};a.a=a.g||a.c}k.return=function(a){this.b={return:a};this.a=this.c};k.yb=function(a){this.b={m:a};this.a=this.c};
function sa(a,b,c){a.a=c;return{value:b}}k.Ub=function(a,b){a=p(a);var c=a.next();ma(c);if(c.done)this.o=c.value,this.a=b;else return this.f=a,sa(this,c.value,b)};k.m=function(a){this.a=a};k.Nb=function(a,b){this.g=a;void 0!=b&&(this.c=b)};k.Pb=function(a){this.g=0;this.c=a||0};k.Ab=function(a,b){this.a=a;this.g=b||0};k.ea=function(a){this.g=a||0;a=this.b.P;this.b=null;return a};k.fa=function(a,b,c){c?this.j[c]=this.b:this.j=[this.b];this.g=a||0;this.c=b||0};
k.zb=function(a,b){b=this.j.splice(b||0)[0];(b=this.b=this.b||b)?b.S?this.a=this.g||this.c:void 0!=b.m&&this.c<b.m?(this.a=b.m,this.b=null):this.a=this.c:this.a=a};k.ma=function(a){return new ta(a)};function ta(a){this.b=a;this.a=[];for(var b in a)this.a.push(b);this.a.reverse()}ta.prototype.c=function(){for(;0<this.a.length;){var a=this.a.pop();if(a in this.b)return a}return null};function ua(a){this.a=new na;this.b=a}
function va(a,b){oa(a.a);var c=a.a.f;if(c)return wa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.a.return);a.a.return(b);return t(a)}function wa(a,b,c,d){try{var e=b.call(a.a.f,c);ma(e);if(!e.done)return a.a.i=!1,e;var g=e.value}catch(f){return a.a.f=null,ra(a.a,f),t(a)}a.a.f=null;d.call(a.a,g);return t(a)}
function t(a){for(;a.a.a;)try{var b=a.b(a.a);if(b)return a.a.i=!1,{value:b.value,done:!1}}catch(c){a.a.o=void 0,ra(a.a,c)}a.a.i=!1;if(a.a.b){b=a.a.b;a.a.b=null;if(b.S)throw b.P;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function xa(a){this.next=function(b){oa(a.a);a.a.f?b=wa(a,a.a.f.next,b,a.a.D):(a.a.D(b),b=t(a));return b};this.throw=function(b){oa(a.a);a.a.f?b=wa(a,a.a.f["throw"],b,a.a.D):(ra(a.a,b),b=t(a));return b};this.return=function(b){return va(a,b)};this[Symbol.iterator]=function(){return this}}function ya(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}new Promise(function(d,e){function g(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(g,e)}g(a.next())})}
r("Object.setPrototypeOf",function(a){return a||ja});function v(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
var za=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=ba(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();r("Reflect.construct",function(){return za});
r("WeakMap",function(a){function b(l){this.a=(h+=Math.random()+1).toString();if(l){l=p(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function e(l){if(!v(l,f)){var m=new c;q(l,f,{value:m})}}function g(l){var m=Object[l];m&&(Object[l]=function(n){if(n instanceof c)return n;e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),n=new a([[l,2],[m,
3]]);if(2!=n.get(l)||3!=n.get(m))return!1;n.delete(l);n.set(m,4);return!n.has(l)&&4==n.get(m)}catch(u){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var h=0;b.prototype.set=function(l,m){if(!d(l))throw Error("Invalid WeakMap key");e(l);if(!v(l,f))throw Error("WeakMap key fail: "+l);l[f][this.a]=m;return this};b.prototype.get=function(l){return d(l)&&v(l,f)?l[f][this.a]:void 0};b.prototype.has=function(l){return d(l)&&v(l,f)&&v(l[f],this.a)};
b.prototype.delete=function(l){return d(l)&&v(l,f)&&v(l[f],this.a)?delete l[f][this.a]:!1};return b});
r("Map",function(a){function b(){var h={};return h.l=h.next=h.head=h}function c(h,l){var m=h.a;return la(function(){if(m){for(;m.head!=h.a;)m=m.l;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})}function d(h,l){var m=l&&typeof l;"object"==m||"function"==m?g.has(l)?m=g.get(l):(m=""+ ++f,g.set(l,m)):m="p_"+l;var n=h.b[m];if(n&&v(h.b,m))for(h=0;h<n.length;h++){var u=n[h];if(l!==l&&u.key!==u.key||l===u.key)return{id:m,list:n,index:h,h:u}}return{id:m,list:n,
index:-1,h:void 0}}function e(h){this.b={};this.a=b();this.size=0;if(h){h=p(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),l=new a(p([[h,"s"]]));if("s"!=l.get(h)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),n=m.next();if(n.done||n.value[0]!=h||"s"!=n.value[1])return!1;n=m.next();return n.done||4!=n.value[0].x||
"t"!=n.value[1]||!m.next().done?!1:!0}catch(u){return!1}}())return a;var g=new WeakMap;e.prototype.set=function(h,l){h=0===h?0:h;var m=d(this,h);m.list||(m.list=this.b[m.id]=[]);m.h?m.h.value=l:(m.h={next:this.a,l:this.a.l,head:this.a,key:h,value:l},m.list.push(m.h),this.a.l.next=m.h,this.a.l=m.h,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.h&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.b[h.id],h.h.l.next=h.h.next,h.h.next.l=h.h.l,h.h.head=null,this.size--,
!0):!1};e.prototype.clear=function(){this.b={};this.a=this.a.l=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).h};e.prototype.get=function(h){return(h=d(this,h).h)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,l){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,
h.call(l,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var f=0;return e});r("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof g){b=g.call(b);for(var f=0;!(g=b.next()).done;)e.push(c.call(d,g.value,f++))}else for(g=b.length,f=0;f<g;f++)e.push(c.call(d,b[f],f));return e}});
r("Set",function(a){function b(c){this.a=new Map;if(c){c=p(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.a.size}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(p([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),g=e.next();if(g.done||g.value[0]!=c||g.value[1]!=c)return!1;g=e.next();return g.done||g.value[0]==c||4!=g.value[0].x||
g.value[1]!=g.value[0]?!1:e.next().done}catch(f){return!1}}())return a;b.prototype.add=function(c){c=0===c?0:c;this.a.set(c,c);this.size=this.a.size;return this};b.prototype.delete=function(c){c=this.a.delete(c);this.size=this.a.size;return c};b.prototype.clear=function(){this.a.clear();this.size=0};b.prototype.has=function(c){return this.a.has(c)};b.prototype.entries=function(){return this.a.entries()};b.prototype.values=function(){return this.a.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.a.forEach(function(g){return c.call(d,g,g,e)})};return b});var w=this||self;function Aa(){}
function y(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function Ba(a){var b=y(a);return"array"==b||"object"==b&&"number"==typeof a.length}function z(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function Ca(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}
function Da(a,b){function c(){}c.prototype=b.prototype;a.C=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ba=function(d,e,g){for(var f=Array(arguments.length-2),h=2;h<arguments.length;h++)f[h-2]=arguments[h];return b.prototype[e].apply(d,f)}};var Ea;var Fa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ga=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},Ha=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,g="string"===typeof a?a.split(""):a,f=0;f<c;f++)if(f in g){var h=g[f];b.call(void 0,h,f,a)&&(d[e++]=h)}return d};function Ia(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Ja=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Ka(a,b){if(b)a=a.replace(La,"&amp;").replace(Ma,"&lt;").replace(Na,"&gt;").replace(Oa,"&quot;").replace(Pa,"&#39;").replace(Qa,"&#0;");else{if(!Ra.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(La,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ma,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Na,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Oa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Pa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Qa,"&#0;"))}return a}
var La=/&/g,Ma=/</g,Na=/>/g,Oa=/"/g,Pa=/'/g,Qa=/\x00/g,Ra=/[\x00&<>"']/;function Sa(a,b){return a<b?-1:a>b?1:0};var A;a:{var Ta=w.navigator;if(Ta){var Ua=Ta.userAgent;if(Ua){A=Ua;break a}}A=""};function Va(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Wa(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}var Xa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ya(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<Xa.length;g++)c=Xa[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function B(a){this.b=Za===Za&&a||"";this.c=$a}B.prototype.L=!0;B.prototype.I=function(){return this.b.toString()};B.prototype.R=!0;B.prototype.a=function(){return 1};var $a={},Za={};function C(){this.b="";this.f=ab;this.c=null}C.prototype.R=!0;C.prototype.a=function(){return this.c};C.prototype.L=!0;C.prototype.I=function(){return this.b.toString()};function D(a){return a instanceof C&&a.constructor===C&&a.f===ab?a.b:"type_error:SafeHtml"}function F(a){if(a instanceof C)return a;var b="object"==typeof a,c=null;b&&a.R&&(c=a.a());return bb(Ka(b&&a.L?a.I():String(a)),c)}
function cb(a){function b(g){Array.isArray(g)?Ga(g,b):(g=F(g),e.push(D(g).toString()),g=g.a(),0==d?d=g:0!=g&&d!=g&&(d=null))}var c=F(db),d=c.a(),e=[];Ga(a,b);return bb(e.join(D(c).toString()),d)}function eb(a){return cb(Array.prototype.slice.call(arguments))}var ab={};function bb(a,b){return fb(a,b)}function fb(a,b){var c=new C;c.b=a;c.c=b;return c}var gb=new C;gb.b=w.trustedTypes&&w.trustedTypes.emptyHTML?w.trustedTypes.emptyHTML:"";gb.c=0;var db=gb,hb=fb("<br>",0);var ib=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=D(db);return!b.parentElement});function jb(a,b){if(ib())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=D(b)};function G(a){return a=Ka(a,void 0)};function kb(a){kb[" "](a);return a}kb[" "]=Aa;function lb(a,b){var c=mb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var nb=-1!=A.indexOf("Opera"),H=-1!=A.indexOf("Trident")||-1!=A.indexOf("MSIE"),ob=-1!=A.indexOf("Edge"),I=-1!=A.indexOf("Gecko")&&!(-1!=A.toLowerCase().indexOf("webkit")&&-1==A.indexOf("Edge"))&&!(-1!=A.indexOf("Trident")||-1!=A.indexOf("MSIE"))&&-1==A.indexOf("Edge"),J=-1!=A.toLowerCase().indexOf("webkit")&&-1==A.indexOf("Edge"),pb=-1!=A.indexOf("Macintosh");function qb(){var a=w.document;return a?a.documentMode:void 0}var rb;
a:{var sb="",tb=function(){var a=A;if(I)return/rv:([^\);]+)(\)|;)/.exec(a);if(ob)return/Edge\/([\d\.]+)/.exec(a);if(H)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(J)return/WebKit\/(\S+)/.exec(a);if(nb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();tb&&(sb=tb?tb[1]:"");if(H){var ub=qb();if(null!=ub&&ub>parseFloat(sb)){rb=String(ub);break a}}rb=sb}var vb=rb,mb={};
function K(a){return lb(a,function(){for(var b=0,c=Ja(String(vb)).split("."),d=Ja(String(a)).split("."),e=Math.max(c.length,d.length),g=0;0==b&&g<e;g++){var f=c[g]||"",h=d[g]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;b=Sa(0==f[1].length?0:parseInt(f[1],10),0==h[1].length?0:parseInt(h[1],10))||Sa(0==f[2].length,0==h[2].length)||Sa(f[2],h[2]);f=f[3];h=h[3]}while(0==b)}return 0<=b})}var wb;
if(w.document&&H){var xb=qb();wb=xb?xb:parseInt(vb,10)||void 0}else wb=void 0;var L=wb;var yb=!H||9<=Number(L),zb=!H||9<=Number(L),Ab=H&&!K("9"),Bb=function(){if(!w.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{w.addEventListener("test",Aa,b),w.removeEventListener("test",Aa,b)}catch(c){}return a}();function M(){this.s=this.s;this.b=this.b}k=M.prototype;k.s=!1;k.Y=function(){return this.s};k.ta=M.prototype.Y;k.O=function(){this.s||(this.s=!0,this.H())};k.Gb=function(a){a=Ca(Cb,a);this.s?a():(this.b||(this.b=[]),this.b.push(a))};k.H=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function Cb(a){a&&"function"==typeof a.O&&a.O()};function N(a,b){this.type=a;this.b=this.target=b;this.A=this.c=!1}N.prototype.J=function(){this.c=!0};N.prototype.w=function(){this.A=!0};var Db;Db=J?"webkitTransitionEnd":nb?"otransitionend":"transitionend";function O(a,b){N.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.j=this.i=0;this.key="";this.f=this.g=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.o=null;this.B=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(I){a:{try{kb(b.nodeName);
var e=!0;break a}catch(g){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.i=J||void 0!==a.offsetX?a.offsetX:a.layerX,this.j=J||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.g=a.keyCode||0;this.key=a.key||"";this.f=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.B=pb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Eb[a.pointerType]||"";this.o=a.state;this.a=a;a.defaultPrevented&&this.w()}}Da(O,N);var Fb=[1,4,2],Eb={2:"touch",3:"pen",4:"mouse"};
O.prototype.T=function(){return(yb?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Fb[0]))&&!(J&&pb&&this.ctrlKey)};O.prototype.J=function(){O.C.J.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};O.prototype.w=function(){O.C.w.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Ab)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};O.prototype.M=function(){return this.a};var Gb="closure_listenable_"+(1E6*Math.random()|0),Hb=0;function Ib(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++Hb;this.u=this.F=!1}function Jb(a){a.u=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function Kb(a){this.src=a;this.a={};this.b=0}k=Kb.prototype;k.fb=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};k.add=function(a,b,c,d,e){var g=a.toString();a=this.a[g];a||(a=this.a[g]=[],this.b++);var f=Lb(a,b,d,e);-1<f?(b=a[f],c||(b.F=!1)):(b=new Ib(b,this.src,g,!!d,e),b.F=c,a.push(b));return b};
k.hb=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Lb(e,b,c,d);return-1<b?(Jb(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};k.ib=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Jb(d[e]);delete this.a[c];this.b--}return b};k.Ga=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
k.gb=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Wa(this.a,function(g){for(var f=0;f<g.length;++f)if(!(c&&g[f].type!=d||e&&g[f].capture!=b))return!0;return!1})};function Lb(a,b,c,d){for(var e=0;e<a.length;++e){var g=a[e];if(!g.u&&g.listener==b&&g.capture==!!c&&g.b==d)return e}return-1};var Mb="closure_lm_"+(1E6*Math.random()|0),Nb={},Ob=0;function Pb(a,b,c,d,e){if(d&&d.once)return Qb(a,b,c,d,e);if(Array.isArray(b)){for(var g=0;g<b.length;g++)Pb(a,b[g],c,d,e);return null}c=Rb(c);return a&&a[Gb]?P(a,b,c,z(d)?!!d.capture:!!d,e):Sb(a,b,c,!1,d,e)}
function Sb(a,b,c,d,e,g){if(!b)throw Error("Invalid event type");var f=z(e)?!!e.capture:!!e,h=Tb(a);h||(a[Mb]=h=new Kb(a));c=h.add(b,c,d,f,g);if(c.a)return c;d=Ub();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Bb||(e=f),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Vb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Ob++;return c}
function Ub(){var a=Wb,b=zb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Qb(a,b,c,d,e){if(Array.isArray(b)){for(var g=0;g<b.length;g++)Qb(a,b[g],c,d,e);return null}c=Rb(c);return a&&a[Gb]?a.A(b,c,z(d)?!!d.capture:!!d,e):Sb(a,b,c,!0,d,e)}
function Xb(a){if("number"!==typeof a&&a&&!a.u){var b=a.src;if(b&&b[Gb])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Vb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Ob--;if(c=Tb(b)){d=a.type;if(d in c.a){var e=c.a[d],g=Fa(e,a),f;(f=0<=g)&&Array.prototype.splice.call(e,g,1);f&&(Jb(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[Mb]=null)}else Jb(a)}}}
function Vb(a){return a in Nb?Nb[a]:Nb[a]="on"+a}function Yb(a,b,c,d){var e=!0;if(a=Tb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.u&&(g=Zb(g,d),e=e&&!1!==g)}return e}function Zb(a,b){var c=a.listener,d=a.b||a.src;a.F&&Xb(a);return c.call(d,b)}
function Wb(a,b){if(a.u)return!0;if(!zb){if(!b)a:{b=["window","event"];for(var c=w,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new O(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(f){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.c&&0<=e;e--){b.b=d[e];var g=Yb(d[e],a,!0,b);c=c&&g}for(e=0;!b.c&&e<d.length;e++)b.b=d[e],g=Yb(d[e],a,!1,b),c=
c&&g}return c}return Zb(a,new O(b,this))}function Tb(a){a=a[Mb];return a instanceof Kb?a:null}var $b="__closure_events_fn_"+(1E9*Math.random()>>>0);function Rb(a){if("function"==y(a))return a;a[$b]||(a[$b]=function(b){return a.handleEvent(b)});return a[$b]};var ac={},bc={};function Q(){throw Error("Do not instantiate directly");}Q.prototype.N=null;Q.prototype.toString=function(){return this.K};Q.prototype.a=function(){if(this.G!==bc)throw Error("Sanitized content was not of kind URI.");return new B(this.toString())};function cc(){Q.call(this)}Da(cc,Q);cc.prototype.G=ac;function dc(){return"Copy link to this section".G===ac};var ec=function(a){function b(c){this.K=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.N=d);return c}}(cc),fc={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function gc(a){return fc[a]}
var hc=/[\x00\x22\x27\x3c\x3e]/g,ic=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,jc=/</g;var kc=!H||9<=Number(L),lc=!I&&!H||H&&9<=Number(L)||I&&K("1.9.1"),mc=H&&!K("9"),nc=H||nb||J;function R(a,b){this.x=void 0!==a?a:0;this.a=void 0!==b?b:0}k=R.prototype;k.jb=function(){return new R(this.x,this.a)};k.ga=function(a){return a instanceof R&&(this==a?!0:this&&a?this.x==a.x&&this.a==a.a:!1)};k.ceil=function(){this.x=Math.ceil(this.x);this.a=Math.ceil(this.a);return this};k.floor=function(){this.x=Math.floor(this.x);this.a=Math.floor(this.a);return this};k.round=function(){this.x=Math.round(this.x);this.a=Math.round(this.a);return this};
k.lb=function(a,b){a instanceof R?(this.x+=a.x,this.a+=a.a):(this.x+=Number(a),"number"===typeof b&&(this.a+=b));return this};k.kb=function(a,b){this.x*=a;this.a*="number"===typeof b?b:a;return this};k.Jb=function(a,b){a=a*Math.PI/180;b=b||new R(0,0);var c=this.x,d=this.a,e=Math.cos(a);a=Math.sin(a);this.x=(c-b.x)*e-(d-b.a)*a+b.x;this.a=(c-b.x)*a+(d-b.a)*e+b.a};function oc(a,b){this.width=a;this.height=b}k=oc.prototype;k.mb=function(){return new oc(this.width,this.height)};k.Ha=function(){return Math.max(this.width,this.height)};k.Ua=function(){return Math.min(this.width,this.height)};k.Fb=function(){return 2*(this.width+this.height)};k.aspectRatio=function(){return this.width/this.height};k.sb=function(){return!(this.width*this.height)};k.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
k.ka=function(a){return this.width<=a.width&&this.height<=a.height};k.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};k.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function pc(a,b){a.width*=b;a.height*=b;return a}k.Lb=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return pc(this,a)};
k.Mb=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return pc(this,a)};function qc(a){return a?new S(T(a)):Ea||(Ea=new S)}function rc(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=sc(document,"*",a,b);return d||null}
function tc(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var g=d=0,f;f=b[g];g++)e==f.nodeName&&(a[d++]=f);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(g=d=0;f=b[g];g++){e=f.className;var h;if(h="function"==typeof e.split)h=0<=Fa(e.split(/\s+/),c);h&&(a[d++]=f)}a.length=d;return a}return b}
function sc(a,b,c,d){var e=d||a,g=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(g||c)?e.querySelector(g+(c?"."+c:"")):tc(a,b,c,d)[0]||null}function uc(a,b){Va(b,function(c,d){c&&"object"==typeof c&&c.L&&(c=c.I());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:vc.hasOwnProperty(d)?a.setAttribute(vc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var vc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function wc(a){a=a.document;a=xc(a)?a.documentElement:a.body;return new oc(a.clientWidth,a.clientHeight)}function yc(a){return a.scrollingElement?a.scrollingElement:!J&&xc(a)?a.documentElement:a.body||a.documentElement}
function zc(a){return a.parentWindow||a.defaultView}function Ac(a,b,c,d){function e(f){f&&b.appendChild("string"===typeof f?a.createTextNode(f):f)}for(;d<c.length;d++){var g=c[d];Ba(g)&&!Bc(g)?Ga(Cc(g)?Ia(g):g,e):e(g)}}function U(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function xc(a){return"CSS1Compat"==a.compatMode}function Dc(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function V(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function Ec(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function Bc(a){return z(a)&&0<a.nodeType}function Fc(a){return z(a)&&1==a.nodeType}function Gc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function Hc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return Ic(b,a)}function Ic(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function T(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function Jc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else Dc(a),a.appendChild(T(a).createTextNode(String(b)))}function Kc(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||Kc(a,b,c,d))return!0;a=a.nextSibling}return!1}var Lc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Mc={IMG:" ",BR:"\n"};
function Nc(a){return Oc(a)&&Pc(a)}function Oc(a){return H&&!K("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function Pc(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function Qc(a){if(mc&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Rc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");mc||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function Rc(a,b,c){if(!(a.nodeName in Lc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Mc)b.push(Mc[a.nodeName]);else for(a=a.firstChild;a;)Rc(a,b,c),a=a.nextSibling}function Cc(a){if(a&&"number"==typeof a.length){if(z(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==y(a))return"function"==typeof a.item}return!1}
function W(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return Sc(a,function(g){var f;(f=!e||g.nodeName==e)&&!(f=!c)&&(f="string"===typeof g.className)&&(f=0<=Fa(g.className.split(/\s+/),c));return f},!0,d)}function Sc(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function S(a){this.a=a||w.document||document}k=S.prototype;k.ya=qc;k.Ob=function(a){this.a=a};k.ua=function(){return this.a};
k.W=function(a){return"string"===typeof a?this.a.getElementById(a):a};k.Sa=function(a){return"string"===typeof a?this.a.getElementById(a):a};k.Z=S.prototype.W;k.ab=function(a,b){return(b||this.a).getElementsByTagName(String(a))};k.X=function(a,b,c){return tc(this.a,a,b,c)};k.Aa=function(a,b,c){return sc(this.a,a,b,c)};k.Ba=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):tc(document,"*",a,b)};k.za=function(a,b){return rc(a,b||this.a)};
k.Ta=function(a,b){return rc(a,b||this.a)};k.$=S.prototype.X;k.Rb=uc;k.Wa=function(a){return wc(a||zc(this.a)||window)};k.va=function(){var a=zc(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=wc(a).height,xc(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
k.V=function(a,b,c){var d=this.a,e=arguments,g=String(e[0]),f=e[1];if(!kc&&f&&(f.name||f.type)){g=["<",g];f.name&&g.push(' name="',G(f.name),'"');if(f.type){g.push(' type="',G(f.type),'"');var h={};Ya(h,f);delete h.type;f=h}g.push(">");g=g.join("")}g=U(d,g);f&&("string"===typeof f?g.className=f:Array.isArray(f)?g.className=f.join(" "):uc(g,f));2<e.length&&Ac(d,g,e,2);return g};k.aa=S.prototype.V;k.$a=function(a){return this.a.createTextNode(String(a))};
k.da=function(a,b,c){var d=this.a;c=!!c;for(var e=U(d,"TABLE"),g=e.appendChild(U(d,"TBODY")),f=0;f<a;f++){for(var h=U(d,"TR"),l=0;l<b;l++){var m=U(d,"TD");c&&Jc(m,"\u00a0");h.appendChild(m)}g.appendChild(h)}return e};k.Kb=function(a){var b=this.a;var c=U(b,"DIV");H?(a=eb(hb,a),jb(c,a),c.removeChild(c.firstChild)):jb(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};k.qb=function(){return xc(this.a)};
k.xa=function(){return yc(this.a)};k.wa=function(){var a=this.a,b=yc(a);a=zc(a);return H&&K("10")&&a.pageYOffset!=b.scrollTop?new R(b.scrollLeft,b.scrollTop):new R(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};k.na=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};k.Ya=function(a,b){a.appendChild(b)};k.Xa=function(a,b){Ac(T(a),a,arguments,1)};k.Za=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
k.Ib=Dc;k.pb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};k.ob=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};k.nb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};k.bb=V;k.cb=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};k.la=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return V(a)}};
k.sa=function(a){return lc&&void 0!=a.children?a.children:Ha(a.childNodes,function(b){return 1==b.nodeType})};k.Ca=function(a){return void 0!==a.firstElementChild?a.firstElementChild:Ec(a.firstChild,!0)};k.Fa=function(a){return void 0!==a.lastElementChild?a.lastElementChild:Ec(a.lastChild,!1)};k.Ia=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:Ec(a.nextSibling,!0)};k.Qa=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:Ec(a.previousSibling,!1)};
k.Ja=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};k.Ra=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};k.vb=Bc;k.rb=Fc;k.xb=function(a){return z(a)&&a.window==a};k.Pa=function(a){var b;if(nc&&!(H&&K("9")&&!K("10")&&w.SVGElement&&a instanceof w.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return Fc(b)?b:null};
k.contains=Gc;
k.ca=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(H&&!(9<=Number(L))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,g=b.parentNode;return e==g?Ic(a,b):!c&&Gc(e,b)?-1*Hc(a,b):!d&&Gc(g,a)?Hc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:g.sourceIndex)}d=T(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(w.Range.START_TO_END,a)};k.ha=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var g=[],f=arguments[b];f;)g.unshift(f),f=f.parentNode;d.push(g);e=Math.min(e,g.length)}g=null;for(b=0;b<e;b++){f=d[0][b];for(var h=1;h<c;h++)if(f!=d[h][b])return g;g=f}return g};k.Oa=T;k.Da=function(a){return a.contentDocument||a.contentWindow.document};
k.Ea=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?zc(c):window}else d=null;b=d}return b}catch(e){}return null};k.Sb=Jc;k.Na=function(a){if("outerHTML"in a)return a.outerHTML;var b=U(T(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};k.ia=function(a,b){var c=[];return Kc(a,b,c,!0)?c[0]:void 0};k.ja=function(a,b){var c=[];Kc(a,b,c,!1);return c};k.ub=Nc;k.Qb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
k.tb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!Oc(a)||Pc(a)):Nc(a))&&H){var c;"function"!=y(a.getBoundingClientRect)||H&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};k.Va=Qc;k.La=function(a){return Qc(a).length};
k.Ma=function(a,b){b=b||T(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(Qc(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
k.Ka=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in Lc))if(3==e.nodeType){var g=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=g.length}else if(e.nodeName in Mc)d+=Mc[e.nodeName].length;else for(g=e.childNodes.length-1;0<=g;g--)a.push(e.childNodes[g]);z(c)&&(c.Hb=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};k.wb=Cc;k.qa=W;k.pa=function(a,b,c){return W(a,null,b,c)};k.oa=Sc;k.ra=function(a){return a.getContext("2d")};function Tc(){return new Promise(function(a){window.requestAnimationFrame(a)})};var Uc=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(Uc&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function X(a){var b=HTMLElement.call(this)||this;a&&Vc(a);return b}ka(X,HTMLElement);X.prototype.M=function(){console.warn(this.tagName,"has not implemented update")};X.prototype.j=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
X.prototype.B=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function Vc(a){"string"===typeof a&&(a=[a]);document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a}))};var Wc=new Map;function Y(a){var b=X.call(this)||this;a&&Vc(a);return b}ka(Y,X);Y.prototype.connectedCallback=function(){var a=this.constructor,b=Wc.get(a);b?console.error("can't add duplicate element to page: "+b.tagName):Wc.set(a,this)};Y.prototype.disconnectedCallback=function(){var a=this.constructor;Wc.get(a)===this&&Wc.delete(a)};Y.prototype.disconnectedCallback=Y.prototype.disconnectedCallback;Y.prototype.connectedCallback=Y.prototype.connectedCallback;function Xc(a,b){window.getSelection().removeAllRanges();var c=document.createElement("pre");c.setAttribute("is-upgraded","");c.style.position="absolute";c.style.top="-99999px";c.style.left="-99999px";c.classList.add("clear-for-copy");Array.from(b.childNodes).forEach(function(d){d.classList&&d.classList.contains("no-select")||c.appendChild(d.cloneNode(!0))});a.appendChild(c);return c}
function Yc(a,b){a=Xc(a,b);b=!1;window.getSelection().selectAllChildren(a);window.getSelection().toString()&&document.queryCommandSupported("copy")&&(document.execCommand("copy"),b=!0);window.getSelection().removeAllRanges();V(a);return b}function Zc(a,b){var c=document.createElement("pre");c.setAttribute("is-upgraded","");b.forEach(function(d){c.appendChild(d.cloneNode(!0))});b=document.querySelector("devsite-snackbar");Yc(a,c)&&b&&b.setAttribute("type","copied-to-clipboard");V(c)};function $c(a){M.call(this);this.c=a;this.a={}}Da($c,M);var ad=[];function bd(a,b,c,d){P(a,b,c,d,void 0)}k=$c.prototype;k.Cb=function(a,b,c,d,e){return P(this,a,b,c,d,e)};function P(a,b,c,d,e,g){Array.isArray(c)||(c&&(ad[0]=c.toString()),c=ad);for(var f=0;f<c.length;f++){var h=Pb(b,c[f],d||a.handleEvent,e||!1,g||a.c||a);if(!h)break;a.a[h.key]=h}return a}function cd(a,b,c,d){dd(a,b,c,d,void 0)}k.Bb=function(a,b,c,d,e){return dd(this,a,b,c,d,e)};
function dd(a,b,c,d,e,g){if(Array.isArray(c))for(var f=0;f<c.length;f++)dd(a,b,c[f],d,e,g);else{b=Qb(b,c,d||a.handleEvent,e,g||a.c||a);if(!b)return a;a.a[b.key]=b}return a}k.Db=function(a,b,c,d){P(b,a,c,d,this.c||this);return this};k.Eb=function(a,b,c,d,e){P(b,a,c,d,e||this.c||this);return this};k.eb=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function ed(a,b,c,d,e,g){if(Array.isArray(c))for(var f=0;f<c.length;f++)ed(a,b,c[f],d,e,g);else d=d||a.handleEvent,e=z(e)?!!e.capture:!!e,g=g||a.c||a,d=Rb(d),e=!!e,b&&b[Gb]?c=b.o(c,d,e,g):b?(b=Tb(b))?(c=b.a[c.toString()],b=-1,c&&(b=Lb(c,d,e,g)),c=-1<b?c[b]:null):c=null:c=null,c&&(Xb(c),delete a.a[c.key])}k.Tb=function(a,b,c,d,e){ed(b,a,c,d,e||this.c||this,this);return this};function fd(a){Va(a.a,function(b,c){this.a.hasOwnProperty(c)&&Xb(b)},a);a.a={}}k.H=function(){$c.C.H.call(this);fd(this)};
k.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function gd(){var a=this;this.a=new Promise(function(b,c){a.resolve=b;a.reject=c})};var hd="onpointermove"in window?"pointermove":"mousemove";
function Z(){var a=Y.call(this)||this;a.a=null;a.f=new Set;a.c=new $c;var b=ec('<button role="button" class="devsite-heading-link button-flat material-icons" aria-label="'+(dc()?String(String("Copy link to this section".K).replace(ic,"").replace(jc,"&lt;")).replace(hc,gc):G("Copy link to this section"))+'" data-title="'+(dc()?String(String("Copy link to this section".K).replace(ic,"").replace(jc,"&lt;")).replace(hc,gc):G("Copy link to this section"))+'"></button>');var c=qc();c=U(c.a,"DIV");if(z(b))if(b instanceof
Q){if(b.G!==ac)throw Error("Sanitized content was not of kind HTML.");b=fb(b.toString(),b.N||null)}else b=F("zSoyz");else b=F(String(b));jb(c,b);1==c.childNodes.length&&(b=c.firstChild,1==b.nodeType&&(c=b));a.b=c;a.i=null;a.g=null;return a}ka(Z,Y);Z.prototype.connectedCallback=function(){Y.prototype.connectedCallback.call(this);id(this);this.g=document.querySelector("devsite-snackbar")};Z.prototype.disconnectedCallback=function(){Y.prototype.disconnectedCallback.call(this);fd(this.c)};
function id(a){bd(a.c,document.body,[hd,"focusin"],function(b){return void jd(a,b)});bd(a.c,a.b,"click",function(b){b.w();b.J();var c=a.a.id;c&&(b=new URL(document.location.toString()),b.hash=c,c=document.createElement("div"),c.innerText=b.href,Zc(a,[c]),V(c),kd(a))})}
function jd(a,b){var c=b.target;c!==a.i&&(a.i=c,c.matches&&c.matches("h1.add-link[id],h2:not(.no-link)[id],h3:not(.no-link)[id],h4:not(.no-link)[id],h5:not(.no-link)[id],h6:not(.no-link)[id]")||(c=Sc(c,function(d){return d instanceof Element?d.matches("h1.add-link[id],h2:not(.no-link)[id],h3:not(.no-link)[id],h4:not(.no-link)[id],h5:not(.no-link)[id],h6:not(.no-link)[id]"):!1},!1,3)),c?(c.classList.contains("add-link")||!("full"===document.body.getAttribute("layout")||W(c,"devsite-dialog",void 0,
3)||W(c,"devsite-selector",void 0,6)||W(c,"table",void 0,4)))&&ld(a,c,b):md(a))}
function ld(a,b,c){var d,e,g;ya(new xa(new ua(function(f){if(1==f.a){if(a.a===b)return f.m(0);a.a=b;d=a.a.dataset.text||a.a.textContent;if(!d)return f.m(0);e="Copy link to this section: "+d;g=a.b;g.dataset.title=e;g.setAttribute("aria-label",e);a.a.appendChild(a.b);a.f.add(a.a);return"focusin"!==c.type?(a.f.forEach(function(h){h.setAttribute("tabindex","0");a.f.delete(h)}),f.m(0)):sa(f,Tc(),5)}a.a&&a.b&&(a.b.focus(),a.a.setAttribute("tabindex","-1"),cd(a.c,a.b,"focusout",function(){a.a.setAttribute("tabindex",
"0");a.f.delete(a.a)}));f.a=0})))}function md(a){a.a&&(a.b.remove(),a.a=null)}function kd(a){var b;ya(new xa(new ua(function(c){if(1==c.a){if(!a.g)return c.m(0);b=new gd;a.b.setAttribute("aria-label","Link to this section was copied to the clipboard");cd(a.c,a.g,Db,function(){b.resolve()});return sa(c,b.a,3)}cd(a.c,a.g,Db,function(){a.b.setAttribute("aria-label","Copy link to this section")});c.a=0})))}Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;
Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-heading-link",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteHeadingLink",a)};}).call(this);
