(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var h;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function fa(a,b){if(b){var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var k;
if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var m;a:{var ha={B:!0},ia={};try{ia.__proto__=ha;m=ia.B;break a}catch(a){}m=!1}k=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var n=k;
function ja(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(n)n(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.i=b.prototype}fa("Object.setPrototypeOf",function(a){return a||n});
var ka=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=ba(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();fa("Reflect.construct",function(){return ka});var p=this||self;
function q(){}
function la(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function r(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ma(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}
function na(a,b){function c(){}c.prototype=b.prototype;a.i=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.G=function(d,e,f){for(var g=Array(arguments.length-2),l=2;l<arguments.length;l++)g[l-2]=arguments[l];return b.prototype[e].apply(d,g)}};var oa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var pa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function t(a,b){return a<b?-1:a>b?1:0};var u;a:{var qa=p.navigator;if(qa){var ra=qa.userAgent;if(ra){u=ra;break a}}u=""};function sa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function ta(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};function v(a){v[" "](a);return a}v[" "]=q;var ua=-1!=u.indexOf("Opera"),w=-1!=u.indexOf("Trident")||-1!=u.indexOf("MSIE"),va=-1!=u.indexOf("Edge"),wa=-1!=u.indexOf("Gecko")&&!(-1!=u.toLowerCase().indexOf("webkit")&&-1==u.indexOf("Edge"))&&!(-1!=u.indexOf("Trident")||-1!=u.indexOf("MSIE"))&&-1==u.indexOf("Edge"),x=-1!=u.toLowerCase().indexOf("webkit")&&-1==u.indexOf("Edge"),xa=-1!=u.indexOf("Macintosh");function ya(){var a=p.document;return a?a.documentMode:void 0}var y;
a:{var z="",A=function(){var a=u;if(wa)return/rv:([^\);]+)(\)|;)/.exec(a);if(va)return/Edge\/([\d\.]+)/.exec(a);if(w)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(x)return/WebKit\/(\S+)/.exec(a);if(ua)return/(?:Version)[ \/]?(\S+)/.exec(a)}();A&&(z=A?A[1]:"");if(w){var B=ya();if(null!=B&&B>parseFloat(z)){y=String(B);break a}}y=z}var za=y,C={},D;if(p.document&&w){var Aa=ya();D=Aa?Aa:parseInt(za,10)||void 0}else D=void 0;var Ba=D;var Ca=!w||9<=Number(Ba),Da=!w||9<=Number(Ba),E;
if(E=w){var F;if(Object.prototype.hasOwnProperty.call(C,"9"))F=C["9"];else{for(var G=0,Ea=pa(String(za)).split("."),Fa=pa("9").split("."),Ga=Math.max(Ea.length,Fa.length),H=0;0==G&&H<Ga;H++){var Ha=Ea[H]||"",Ia=Fa[H]||"";do{var I=/(\d*)(\D*)(.*)/.exec(Ha)||["","","",""],J=/(\d*)(\D*)(.*)/.exec(Ia)||["","","",""];if(0==I[0].length&&0==J[0].length)break;G=t(0==I[1].length?0:parseInt(I[1],10),0==J[1].length?0:parseInt(J[1],10))||t(0==I[2].length,0==J[2].length)||t(I[2],J[2]);Ha=I[3];Ia=J[3]}while(0==
G)}F=C["9"]=0<=G}E=!F}var Ja=E,Ka=function(){if(!p.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{p.addEventListener("test",q,b),p.removeEventListener("test",q,b)}catch(c){}return a}();function K(){this.f=this.f;this.b=this.b}h=K.prototype;h.f=!1;h.C=function(){return this.f};h.H=K.prototype.C;h.o=function(){this.f||(this.f=!0,this.l())};h.U=function(a){a=ma(La,a);this.f?a():(this.b||(this.b=[]),this.b.push(a))};h.l=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function La(a){a&&"function"==typeof a.o&&a.o()};function L(a,b){this.type=a;this.b=this.target=b;this.D=this.c=!1}L.prototype.m=function(){this.c=!0};L.prototype.h=function(){this.D=!0};function M(a,b){L.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.w=this.v=0;this.key="";this.u=this.s=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.A=null;this.F=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(wa){a:{try{v(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.v=x||void 0!==a.offsetX?a.offsetX:a.layerX,this.w=x||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.s=a.keyCode||0;this.key=a.key||"";this.u=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.F=xa?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Ma[a.pointerType]||"";this.A=a.state;this.a=a;a.defaultPrevented&&this.h()}}na(M,L);var Na=[1,4,2],Ma={2:"touch",3:"pen",4:"mouse"};
M.prototype.W=function(){return(Ca?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Na[0]))&&!(x&&xa&&this.ctrlKey)};M.prototype.m=function(){M.i.m.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};M.prototype.h=function(){M.i.h.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Ja)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};M.prototype.V=function(){return this.a};var N="closure_listenable_"+(1E6*Math.random()|0),Oa=0;function Pa(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++Oa;this.g=this.j=!1}function O(a){a.g=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function P(a){this.src=a;this.a={};this.b=0}h=P.prototype;h.L=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};h.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Q(a,b,d,e);-1<g?(b=a[g],c||(b.j=!1)):(b=new Pa(b,this.src,f,!!d,e),b.j=c,a.push(b));return b};
h.N=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Q(e,b,c,d);return-1<b?(O(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};h.O=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,O(d[e]);delete this.a[c];this.b--}return b};h.I=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
h.M=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return ta(this.a,function(f){for(var g=0;g<f.length;++g)if(!(c&&f[g].type!=d||e&&f[g].capture!=b))return!0;return!1})};function Q(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.g&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var R="closure_lm_"+(1E6*Math.random()|0),S={},Qa=0;function Ra(a,b,c,d,e){if(d&&d.once)return T(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)Ra(a,b[f],c,d,e);return null}c=U(c);return a&&a[N]?V(a,b,c,r(d)?!!d.capture:!!d,e):Sa(a,b,c,!1,d,e)}
function Sa(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=r(e)?!!e.capture:!!e,l=W(a);l||(a[R]=l=new P(a));c=l.add(b,c,d,g,f);if(c.a)return c;d=Ta();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Ka||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Ua(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Qa++;return c}
function Ta(){var a=Va,b=Da?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function T(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)T(a,b[f],c,d,e);return null}c=U(c);return a&&a[N]?a.v(b,c,r(d)?!!d.capture:!!d,e):Sa(a,b,c,!0,d,e)}
function Wa(a){if("number"!==typeof a&&a&&!a.g){var b=a.src;if(b&&b[N])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Ua(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Qa--;if(c=W(b)){d=a.type;if(d in c.a){var e=c.a[d],f=oa(e,a),g;(g=0<=f)&&Array.prototype.splice.call(e,f,1);g&&(O(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[R]=null)}else O(a)}}}function Ua(a){return a in S?S[a]:S[a]="on"+a}
function Xa(a,b,c,d){var e=!0;if(a=W(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.g&&(f=Ya(f,d),e=e&&!1!==f)}return e}function Ya(a,b){var c=a.listener,d=a.b||a.src;a.j&&Wa(a);return c.call(d,b)}
function Va(a,b){if(a.g)return!0;if(!Da){if(!b)a:{b=["window","event"];for(var c=p,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new M(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.c&&0<=e;e--){b.b=d[e];var f=Xa(d[e],a,!0,b);c=c&&f}for(e=0;!b.c&&e<d.length;e++)b.b=d[e],f=Xa(d[e],a,!1,b),c=
c&&f}return c}return Ya(a,new M(b,this))}function W(a){a=a[R];return a instanceof P?a:null}var Za="__closure_events_fn_"+(1E9*Math.random()>>>0);function U(a){if("function"==la(a))return a;a[Za]||(a[Za]=function(b){return a.handleEvent(b)});return a[Za]};var $a=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if($a&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function X(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ja(X,HTMLElement);X.prototype.A=function(){console.warn(this.tagName,"has not implemented update")};X.prototype.m=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
X.prototype.w=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function Y(a){K.call(this);this.c=a;this.a={}}na(Y,K);var ab=[];function bb(a,b,c){V(a,b,["click","keypress"],c,void 0)}h=Y.prototype;h.R=function(a,b,c,d,e){return V(this,a,b,c,d,e)};function V(a,b,c,d,e,f){Array.isArray(c)||(c&&(ab[0]=c.toString()),c=ab);for(var g=0;g<c.length;g++){var l=Ra(b,c[g],d||a.handleEvent,e||!1,f||a.c||a);if(!l)break;a.a[l.key]=l}return a}h.K=function(a,b,c,d){return cb(this,a,b,c,d)};h.P=function(a,b,c,d,e){return cb(this,a,b,c,d,e)};
function cb(a,b,c,d,e,f){if(Array.isArray(c))for(var g=0;g<c.length;g++)cb(a,b,c[g],d,e,f);else{b=T(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}h.S=function(a,b,c,d){V(b,a,c,d,this.c||this);return this};h.T=function(a,b,c,d,e){V(b,a,c,d,e||this.c||this);return this};h.J=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function db(a,b,c,d,e,f){if(Array.isArray(c))for(var g=0;g<c.length;g++)db(a,b,c[g],d,e,f);else d=d||a.handleEvent,e=r(e)?!!e.capture:!!e,f=f||a.c||a,d=U(d),e=!!e,b&&b[N]?c=b.u(c,d,e,f):b?(b=W(b))?(c=b.a[c.toString()],b=-1,c&&(b=Q(c,d,e,f)),c=-1<b?c[b]:null):c=null:c=null,c&&(Wa(c),delete a.a[c.key])}h.X=function(a,b,c,d,e){db(b,a,c,d,e||this.c||this,this);return this};function eb(a){sa(a.a,function(b,c){this.a.hasOwnProperty(c)&&Wa(b)},a);a.a={}}h.l=function(){Y.i.l.call(this);eb(this)};
h.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Z(){var a=X.call(this)||this;a.b=new Y;a.c=!1;a.a=null;return a}ja(Z,X);
Z.prototype.connectedCallback=function(){var a=this.querySelector(".expandable");if(a){var b=a.getAttribute("id");b&&this.setAttribute("id",b);a.classList.contains("expanded")&&this.setAttribute("expanded","");b=a.attributes;var c="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];b=c?c.call(b):{next:aa(b)};for(c=b.next();!c.done;c=b.next())c=c.value,"class"!==c.name&&"id"!==c.name&&this.setAttribute(c.name,c.value);for(;a.childNodes.length;)this.appendChild(a.childNodes[0]);a&&a.parentNode&&
a.parentNode.removeChild(a)}if(!this.c){b=this.getAttribute("id");a=this.hasAttribute("expanded")?"true":"false";if(b)(new URL(document.location.toString())).hash==="#"+b&&this.setAttribute("expanded","");else{b=1;for(c="expandable-"+b;document.getElementById(c);)c="expandable-"+b++;b=this.id=c}this.a=this.querySelector(".expand-control");this.a||(this.a=document.createElement("a"),this.a.classList.add("exw-control"),this.hasAttribute("once")&&this.a.classList.add("once"),this.insertBefore(this.a,
this.childNodes[0]||null));this.a.setAttribute("aria-controls",b);this.a.setAttribute("aria-expanded",a);this.a.setAttribute("tabindex",0);"button"!==this.a.tagName.toLowerCase()&&this.a.setAttribute("role","button");if(a=this.querySelector(".showalways"))a.id=b+"-label",this.a.setAttribute("aria-labelledby",b+"-label");this.parentElement.classList.add("expandable-container");this.c=!0}fb(this)};Z.prototype.disconnectedCallback=function(){eb(this.b)};
function fb(a){bb(a.b,a.a,function(b){if("keypress"!==b.type||13===b.s){b.h();if(a.hasAttribute("expanded"))a.removeAttribute("expanded"),a.a.setAttribute("aria-expanded","false");else if(a.setAttribute("expanded",""),a.a.setAttribute("aria-expanded","true"),a.a.classList.contains("once")){var c=a.a;c&&c.parentNode&&c.parentNode.removeChild(c)}a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"devsite-expandable "+b.type,label:"expanded: "+
a.hasAttribute("expanded")},bubbles:!0}));a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))}})}Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-expandable",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteExpandable",a)};}).call(this);
