(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function ea(a,b){if(b){var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={ca:!0},ja={};try{ja.__proto__=ia;ha=ja.ca;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function la(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.v=b.prototype}ea("Object.setPrototypeOf",function(a){return a||ka});
var ma=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=aa(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();ea("Reflect.construct",function(){return ma});var l=this||self;
function na(){}
function oa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function pa(a){var b=oa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function m(a){return"function"==oa(a)}function n(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function qa(a){return Object.prototype.hasOwnProperty.call(a,ra)&&a[ra]||(a[ra]=++sa)}var ra="closure_uid_"+(1E9*Math.random()>>>0),sa=0;function ta(a,b,c){return a.call.apply(a.bind,arguments)}
function ua(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function p(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?p=ta:p=ua;return p.apply(null,arguments)}
function va(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var wa=Date.now||function(){return+new Date};function r(a,b){function c(){}c.prototype=b.prototype;a.v=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.sa=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var xa;var ya=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},za=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},Aa=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d},Ba=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d};function Ca(a,b){return 0<=ya(a,b)}
function Da(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Ea=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Fa(a,b){if(b)a=a.replace(Ga,"&amp;").replace(Ha,"&lt;").replace(Ia,"&gt;").replace(Ja,"&quot;").replace(Ka,"&#39;").replace(La,"&#0;");else{if(!Ma.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ga,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ha,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ia,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ja,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ka,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(La,"&#0;"))}return a}
var Ga=/&/g,Ha=/</g,Ia=/>/g,Ja=/"/g,Ka=/'/g,La=/\x00/g,Ma=/[\x00&<>"']/;function Na(a,b){return a<b?-1:a>b?1:0};var t;a:{var Oa=l.navigator;if(Oa){var Pa=Oa.userAgent;if(Pa){t=Pa;break a}}t=""};function Qa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ra(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}function Sa(){var a=u,b;for(b in a)return!1;return!0}var Ta="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ua(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ta.length;f++)c=Ta[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function v(){this.b="";this.c=Va;this.a=null}v.prototype.ha=!0;v.prototype.$=!0;v.prototype.Y=function(){return this.b.toString()};function Wa(a){return a instanceof v&&a.constructor===v&&a.c===Va?a.b:"type_error:SafeHtml"}function Xa(a){if(a instanceof v)return a;var b="object"==typeof a,c=null;b&&a.ha&&(c=a.a);return Ya(Fa(b&&a.$?a.Y():String(a)),c)}
function Za(a){function b(f){Array.isArray(f)?za(f,b):(f=Xa(f),e.push(Wa(f).toString()),f=f.a,0==d?d=f:0!=f&&d!=f&&(d=null))}var c=Xa($a),d=c.a,e=[];za(a,b);return Ya(e.join(Wa(c).toString()),d)}function ab(a){return Za(Array.prototype.slice.call(arguments))}var Va={};function Ya(a,b){return bb(a,b)}function bb(a,b){var c=new v;c.b=a;c.a=b;return c}var cb=new v;cb.b=l.trustedTypes&&l.trustedTypes.emptyHTML?l.trustedTypes.emptyHTML:"";cb.a=0;var $a=cb,db=bb("<br>",0);var eb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=Wa($a);return!b.parentElement});function fb(a,b){if(eb())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=Wa(b)};function gb(a){return a=Fa(a,void 0)};function hb(a){hb[" "](a);return a}hb[" "]=na;function ib(a,b){var c=jb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var kb=-1!=t.indexOf("Opera"),w=-1!=t.indexOf("Trident")||-1!=t.indexOf("MSIE"),x=-1!=t.indexOf("Edge"),y=-1!=t.indexOf("Gecko")&&!(-1!=t.toLowerCase().indexOf("webkit")&&-1==t.indexOf("Edge"))&&!(-1!=t.indexOf("Trident")||-1!=t.indexOf("MSIE"))&&-1==t.indexOf("Edge"),z=-1!=t.toLowerCase().indexOf("webkit")&&-1==t.indexOf("Edge"),A=-1!=t.indexOf("Macintosh");function lb(){var a=l.document;return a?a.documentMode:void 0}var mb;
a:{var nb="",ob=function(){var a=t;if(y)return/rv:([^\);]+)(\)|;)/.exec(a);if(x)return/Edge\/([\d\.]+)/.exec(a);if(w)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(z)return/WebKit\/(\S+)/.exec(a);if(kb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ob&&(nb=ob?ob[1]:"");if(w){var pb=lb();if(null!=pb&&pb>parseFloat(nb)){mb=String(pb);break a}}mb=nb}var qb=mb,jb={};
function B(a){return ib(a,function(){for(var b=0,c=Ea(String(qb)).split("."),d=Ea(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=Na(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||Na(0==h[2].length,0==k[2].length)||Na(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var rb;
if(l.document&&w){var sb=lb();rb=sb?sb:parseInt(qb,10)||void 0}else rb=void 0;var C=rb;var tb=!w||9<=Number(C),ub=!w||9<=Number(C),vb=w&&!B("9"),wb=function(){if(!l.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{l.addEventListener("test",na,b),l.removeEventListener("test",na,b)}catch(c){}return a}();function D(){this.D=this.D;this.m=this.m}g=D.prototype;g.D=!1;g.ia=function(){return this.D};g.Ja=D.prototype.ia;g.R=function(){this.D||(this.D=!0,this.i())};g.dc=function(a){a=va(xb,a);this.D?a():(this.m||(this.m=[]),this.m.push(a))};g.i=function(){if(this.m)for(;this.m.length;)this.m.shift()()};function xb(a){a&&"function"==typeof a.R&&a.R()};function E(a,b){this.type=a;this.c=this.target=b;this.defaultPrevented=this.f=!1}E.prototype.stopPropagation=function(){this.f=!0};E.prototype.preventDefault=function(){this.defaultPrevented=!0};function F(a,b){E.call(this,a?a.type:"");this.relatedTarget=this.c=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.o=this.m=0;this.key="";this.g=this.a=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.u=null;this.G=!1;this.pointerId=0;this.pointerType="";this.b=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.c=b;if(b=a.relatedTarget){if(y){a:{try{hb(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.m=z||void 0!==a.offsetX?a.offsetX:a.layerX,this.o=z||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.a=a.keyCode||0;this.key=a.key||"";this.g=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.G=A?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:yb[a.pointerType]||"";this.u=a.state;this.b=a;a.defaultPrevented&&this.preventDefault()}}r(F,E);var zb=[1,4,2],yb={2:"touch",3:"pen",4:"mouse"};
F.prototype.N=function(){return(tb?0==this.b.button:"click"==this.type?!0:!!(this.b.button&zb[0]))&&!(z&&A&&this.ctrlKey)};F.prototype.stopPropagation=function(){F.v.stopPropagation.call(this);this.b.stopPropagation?this.b.stopPropagation():this.b.cancelBubble=!0};F.prototype.preventDefault=function(){F.v.preventDefault.call(this);var a=this.b;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,vb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Ab="closure_listenable_"+(1E6*Math.random()|0);function G(a){return!(!a||!a[Ab])}var Bb=0;function Cb(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.K=e;this.key=++Bb;this.H=this.J=!1}function Db(a){a.H=!0;a.listener=null;a.a=null;a.src=null;a.K=null};function H(a){this.src=a;this.a={};this.b=0}H.prototype.c=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};H.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=Eb(a,b,d,e);-1<h?(b=a[h],c||(b.J=!1)):(b=new Cb(b,this.src,f,!!d,e),b.J=c,a.push(b));return b};
function Fb(a,b){var c=b.type;if(!(c in a.a))return!1;var d=a.a[c],e=ya(d,b),f;(f=0<=e)&&Array.prototype.splice.call(d,e,1);f&&(Db(b),0==a.a[c].length&&(delete a.a[c],a.b--));return f}function Gb(a){var b=0,c;for(c in a.a){for(var d=a.a[c],e=0;e<d.length;e++)++b,Db(d[e]);delete a.a[c];a.b--}}function Hb(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Eb(a,c,d,e));return-1<b?a[b]:null}
function Ib(a,b,c){var d=void 0!==b,e=d?b.toString():"",f=void 0!==c;return Ra(a.a,function(h){for(var k=0;k<h.length;++k)if(!(d&&h[k].type!=e||f&&h[k].capture!=c))return!0;return!1})}function Eb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.H&&f.listener==b&&f.capture==!!c&&f.K==d)return e}return-1};var Jb="closure_lm_"+(1E6*Math.random()|0),Kb={},Lb=0;function I(a,b,c,d,e){if(d&&d.once)return Mb(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)I(a,b[f],c,d,e);return null}c=Nb(c);return G(a)?a.B(b,c,n(d)?!!d.capture:!!d,e):Ob(a,b,c,!1,d,e)}
function Ob(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=n(e)?!!e.capture:!!e,k=J(a);k||(a[Jb]=k=new H(a));c=k.add(b,c,d,h,f);if(c.a)return c;d=Pb();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)wb||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Qb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Lb++;return c}
function Pb(){var a=Rb,b=ub?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Mb(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)Mb(a,b[f],c,d,e);return null}c=Nb(c);return G(a)?a.j.add(String(b),c,!0,n(d)?!!d.capture:!!d,e):Ob(a,b,c,!0,d,e)}
function Sb(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Sb(a,b[f],c,d,e);else d=n(d)?!!d.capture:!!d,c=Nb(c),G(a)?a.O(b,c,d,e):a&&(a=J(a))&&(b=Hb(a,b,c,d,e))&&K(b)}
function K(a){if("number"===typeof a||!a||a.H)return!1;var b=a.src;if(G(b))return Fb(b.j,a);var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Qb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Lb--;(c=J(b))?(Fb(c,a),0==c.b&&(c.src=null,b[Jb]=null)):Db(a);return!0}function Tb(a){if(a)if(G(a))a.j&&Gb(a.j);else if(a=J(a)){var b=0,c;for(c in a.a)for(var d=a.a[c].concat(),e=0;e<d.length;++e)K(d[e])&&++b}}
function Qb(a){return a in Kb?Kb[a]:Kb[a]="on"+a}function Ub(a,b,c,d){var e=!0;if(a=J(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.H&&(f=Vb(f,d),e=e&&!1!==f)}return e}function Vb(a,b){var c=a.listener,d=a.K||a.src;a.J&&K(a);return c.call(d,b)}
function Rb(a,b){if(a.H)return!0;if(!ub){if(!b)a:{b=["window","event"];for(var c=l,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new F(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.c;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.f&&0<=e;e--){b.c=d[e];var f=Ub(d[e],a,!0,b);c=c&&f}for(e=0;!b.f&&e<d.length;e++)b.c=d[e],f=Ub(d[e],a,!1,b),c=
c&&f}return c}return Vb(a,new F(b,this))}function J(a){a=a[Jb];return a instanceof H?a:null}var Wb="__closure_events_fn_"+(1E9*Math.random()>>>0);function Nb(a){if(m(a))return a;a[Wb]||(a[Wb]=function(b){return a.handleEvent(b)});return a[Wb]};var Xb=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(Xb&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function L(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}la(L,HTMLElement);L.prototype.f=function(){console.warn(this.tagName,"has not implemented update")};L.prototype.b=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
L.prototype.c=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};var Yb;var Zb=!w||9<=Number(C),$b=!y&&!w||w&&9<=Number(C)||y&&B("1.9.1"),ac=w&&!B("9"),bc=w||kb||z;function M(a,b){this.a=void 0!==a?a:0;this.b=void 0!==b?b:0}g=M.prototype;g.Fb=function(){return new M(this.a,this.b)};g.xa=function(a){return a instanceof M&&(this==a?!0:this&&a?this.a==a.a&&this.b==a.b:!1)};g.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);return this};g.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);return this};g.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);return this};
g.Hb=function(a,b){a instanceof M?(this.a+=a.a,this.b+=a.b):(this.a+=Number(a),"number"===typeof b&&(this.b+=b));return this};g.Gb=function(a,b){this.a*=a;this.b*="number"===typeof b?b:a;return this};g.hc=function(a,b){a=a*Math.PI/180;b=b||new M(0,0);var c=this.a,d=this.b,e=Math.cos(a);a=Math.sin(a);this.a=(c-b.a)*e-(d-b.b)*a+b.a;this.b=(c-b.a)*a+(d-b.b)*e+b.b};function cc(a,b){this.width=a;this.height=b}g=cc.prototype;g.Ib=function(){return new cc(this.width,this.height)};g.Xa=function(){return Math.max(this.width,this.height)};g.kb=function(){return Math.min(this.width,this.height)};g.cc=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.Qb=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.Ba=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function dc(a,b){a.width*=b;a.height*=b;return a}g.jc=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return dc(this,a)};
g.kc=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return dc(this,a)};function ec(a){return a?new N(O(a)):xa||(xa=new N)}function fc(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=gc(document,"*",a,b);return d||null}
function hc(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&Ca(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a}
function gc(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):hc(a,b,c,d)[0]||null}function ic(a,b){Qa(b,function(c,d){c&&"object"==typeof c&&c.$&&(c=c.Y());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:jc.hasOwnProperty(d)?a.setAttribute(jc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var jc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function kc(a){a=a.document;a=lc(a)?a.documentElement:a.body;return new cc(a.clientWidth,a.clientHeight)}function mc(a){return a.scrollingElement?a.scrollingElement:!z&&lc(a)?a.documentElement:a.body||a.documentElement}
function nc(a){return a.parentWindow||a.defaultView}function oc(a,b,c,d){function e(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];pa(f)&&!pc(f)?za(qc(f)?Da(f):f,e):e(f)}}function P(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function lc(a){return"CSS1Compat"==a.compatMode}function rc(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function sc(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function uc(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function pc(a){return n(a)&&0<a.nodeType}function vc(a){return n(a)&&1==a.nodeType}function wc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function xc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return yc(b,a)}function yc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function O(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function zc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else rc(a),a.appendChild(O(a).createTextNode(String(b)))}function Ac(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||Ac(a,b,c,d))return!0;a=a.nextSibling}return!1}var Bc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Cc={IMG:" ",BR:"\n"};
function Dc(a){return Ec(a)&&Fc(a)}function Ec(a){return w&&!B("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function Fc(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function Gc(a){if(ac&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Hc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");ac||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function Hc(a,b,c){if(!(a.nodeName in Bc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Cc)b.push(Cc[a.nodeName]);else for(a=a.firstChild;a;)Hc(a,b,c),a=a.nextSibling}function qc(a){if(a&&"number"==typeof a.length){if(n(a))return"function"==typeof a.item||"string"==typeof a.item;if(m(a))return"function"==typeof a.item}return!1}
function Ic(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return Jc(a,function(f){return(!e||f.nodeName==e)&&(!c||"string"===typeof f.className&&Ca(f.className.split(/\s+/),c))},!0,d)}function Jc(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function N(a){this.a=a||l.document||document}g=N.prototype;g.Oa=ec;g.lc=function(a){this.a=a};g.Ka=function(){return this.a};
g.I=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.ib=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.oa=N.prototype.I;g.wb=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.ea=function(a,b,c){return hc(this.a,a,b,c)};g.Ra=function(a,b,c){return gc(this.a,a,b,c)};g.Sa=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):hc(document,"*",a,b)};g.Qa=function(a,b){return fc(a,b||this.a)};
g.jb=function(a,b){return fc(a,b||this.a)};g.pa=N.prototype.ea;g.rc=ic;g.mb=function(a){return kc(a||nc(this.a)||window)};g.La=function(){var a=nc(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=kc(a).height,lc(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.X=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!Zb&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',gb(h.name),'"');if(h.type){f.push(' type="',gb(h.type),'"');var k={};Ua(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=P(d,f);h&&("string"===typeof h?f.className=h:Array.isArray(h)?f.className=h.join(" "):ic(f,h));2<e.length&&oc(d,f,e,2);return f};g.qa=N.prototype.X;g.ub=function(a){return P(this.a,a)};g.vb=function(a){return this.a.createTextNode(String(a))};
g.ua=function(a,b,c){var d=this.a;c=!!c;for(var e=P(d,"TABLE"),f=e.appendChild(P(d,"TBODY")),h=0;h<a;h++){for(var k=P(d,"TR"),q=0;q<b;q++){var tc=P(d,"TD");c&&zc(tc,"\u00a0");k.appendChild(tc)}f.appendChild(k)}return e};g.ic=function(a){var b=this.a;var c=P(b,"DIV");w?(a=ab(db,a),fb(c,a),c.removeChild(c.firstChild)):fb(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.Ob=function(){return lc(this.a)};
g.Na=function(){return mc(this.a)};g.Ma=function(){var a=this.a,b=mc(a);a=nc(a);return w&&B("10")&&a.pageYOffset!=b.scrollTop?new M(b.scrollLeft,b.scrollTop):new M(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};g.Da=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.rb=function(a,b){a.appendChild(b)};g.qb=function(a,b){oc(O(a),a,arguments,1)};g.sb=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.fc=rc;g.Mb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.Lb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.Kb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.xb=sc;g.yb=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.Ca=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return sc(a)}};
g.Ia=function(a){return $b&&void 0!=a.children?a.children:Aa(a.childNodes,function(b){return 1==b.nodeType})};g.Ta=function(a){return void 0!==a.firstElementChild?a.firstElementChild:uc(a.firstChild,!0)};g.Wa=function(a){return void 0!==a.lastElementChild?a.lastElementChild:uc(a.lastChild,!1)};g.Ya=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:uc(a.nextSibling,!0)};g.gb=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:uc(a.previousSibling,!1)};
g.Za=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.hb=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.Vb=pc;g.Pb=vc;g.Yb=function(a){return n(a)&&a.window==a};g.fb=function(a){var b;if(bc&&!(w&&B("9")&&!B("10")&&l.SVGElement&&a instanceof l.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return vc(b)?b:null};
g.tb=wc;
g.ta=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(w&&!(9<=Number(C))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?yc(a,b):!c&&wc(e,b)?-1*xc(a,b):!d&&wc(f,a)?xc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=O(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(l.Range.START_TO_END,a)};g.ya=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){h=d[0][b];for(var k=1;k<c;k++)if(h!=d[k][b])return f;f=h}return f};g.eb=O;g.Ua=function(a){return a.contentDocument||a.contentWindow.document};
g.Va=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?nc(c):window}else d=null;b=d}return b}catch(e){}return null};g.tc=zc;g.cb=function(a){if("outerHTML"in a)return a.outerHTML;var b=P(O(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.za=function(a,b){var c=[];return Ac(a,b,c,!0)?c[0]:void 0};g.Aa=function(a,b){var c=[];Ac(a,b,c,!1);return c};g.Sb=Dc;g.mc=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.Rb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!Ec(a)||Fc(a)):Dc(a))&&w){var c;!m(a.getBoundingClientRect)||w&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.lb=Gc;g.ab=function(a){return Gc(a).length};
g.bb=function(a,b){b=b||O(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(Gc(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.$a=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in Bc))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in Cc)d+=Cc[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);n(c)&&(c.ec=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.Wb=qc;g.Ga=Ic;g.Fa=function(a,b,c){return Ic(a,null,b,c)};g.Ea=Jc;g.Ha=function(a){return a.getContext("2d")};function Kc(a,b){b?a.setAttribute("role",b):a.removeAttribute("role")};function Lc(a){return"string"==typeof a.className?a.className:a.getAttribute&&a.getAttribute("class")||""}function Mc(a,b){"string"==typeof a.className?a.className=b:a.setAttribute&&a.setAttribute("class",b)}function Nc(a,b){return a.classList?a.classList.contains(b):Ca(a.classList?a.classList:Lc(a).match(/\S+/g)||[],b)}function Q(a,b){if(a.classList)a.classList.add(b);else if(!Nc(a,b)){var c=Lc(a);Mc(a,c+(0<c.length?" "+b:b))}}
function Oc(a,b){a.classList?a.classList.remove(b):Nc(a,b)&&Mc(a,Aa(a.classList?a.classList:Lc(a).match(/\S+/g)||[],function(c){return c!=b}).join(" "))};function R(a){D.call(this);this.b=a;this.a={}}r(R,D);var Pc=[];g=R.prototype;g.B=function(a,b,c,d){return Qc(this,a,b,c,d)};g.$b=function(a,b,c,d,e){return Qc(this,a,b,c,d,e)};function Qc(a,b,c,d,e,f){Array.isArray(c)||(c&&(Pc[0]=c.toString()),c=Pc);for(var h=0;h<c.length;h++){var k=I(b,c[h],d||a.handleEvent,e||!1,f||a.b||a);if(!k)break;a.a[k.key]=k}return a}g.Ab=function(a,b,c,d){return Rc(this,a,b,c,d)};g.Zb=function(a,b,c,d,e){return Rc(this,a,b,c,d,e)};
function Rc(a,b,c,d,e,f){if(Array.isArray(c))for(var h=0;h<c.length;h++)Rc(a,b,c[h],d,e,f);else{b=Mb(b,c,d||a.handleEvent,e,f||a.b||a);if(!b)return a;a.a[b.key]=b}return a}g.ac=function(a,b,c,d){b.B(a,c,d,this.b||this);return this};g.bc=function(a,b,c,d,e){b.B(a,c,d,e||this.b||this);return this};g.zb=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
g.O=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)this.O(a,b[f],c,d,e);else c=c||this.handleEvent,d=n(d)?!!d.capture:!!d,e=e||this.b||this,c=Nb(c),d=!!d,b=G(a)?Hb(a.j,String(b),c,d,e):a?(a=J(a))?Hb(a,b,c,d,e):null:null,b&&(K(b),delete this.a[b.key])};g.uc=function(a,b,c,d,e){b.O(a,c,d,e||this.b||this,this);return this};function Sc(a){Qa(a.a,function(b,c){this.a.hasOwnProperty(c)&&K(b)},a);a.a={}}g.i=function(){R.v.i.call(this);Sc(this)};
g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function S(){D.call(this);this.j=new H(this);this.aa=this;this.G=null}r(S,D);S.prototype[Ab]=!0;g=S.prototype;g.pc=function(a){this.G=a};g.addEventListener=function(a,b,c,d){I(this,a,b,c,d)};g.removeEventListener=function(a,b,c,d){Sb(this,a,b,c,d)};
function T(a,b){var c,d=a.G;if(d)for(c=[];d;d=d.G)c.push(d);a=a.aa;d=b.type||b;if("string"===typeof b)b=new E(b,a);else if(b instanceof E)b.target=b.target||a;else{var e=b;b=new E(d,a);Ua(b,e)}e=!0;if(c)for(var f=c.length-1;!b.f&&0<=f;f--){var h=b.c=c[f];e=Tc(h,d,!0,b)&&e}b.f||(h=b.c=a,e=Tc(h,d,!0,b)&&e,b.f||(e=Tc(h,d,!1,b)&&e));if(c)for(f=0;!b.f&&f<c.length;f++)h=b.c=c[f],e=Tc(h,d,!1,b)&&e}g.i=function(){S.v.i.call(this);this.j&&Gb(this.j);this.G=null};
g.B=function(a,b,c,d){return this.j.add(String(a),b,!1,c,d)};g.O=function(a,b,c,d){var e=this.j;a=String(a).toString();if(a in e.a){var f=e.a[a];b=Eb(f,b,c,d);-1<b&&(Db(f[b]),Array.prototype.splice.call(f,b,1),0==f.length&&(delete e.a[a],e.b--))}};function Tc(a,b,c,d){b=a.j.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var h=b[f];if(h&&!h.H&&h.capture==c){var k=h.listener,q=h.K||h.src;h.J&&Fb(a.j,h);e=!1!==k.call(q,d)&&e}}return e&&!d.defaultPrevented}
g.Bb=function(a,b){a=this.j.a[String(a).toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};g.Cb=function(a,b){return Ib(this.j,void 0!==a?String(a):void 0,b)};g.sc=function(a){this.aa=a};g.ra=function(){};function Uc(a,b,c){D.call(this);this.a=a;this.f=b||0;this.b=c;this.c=p(this.Z,this)}r(Uc,D);g=Uc.prototype;g.w=0;g.i=function(){Uc.v.i.call(this);Vc(this);delete this.a;delete this.b};g.start=function(a){Vc(this);var b=this.c;a=void 0!==a?a:this.f;if(!m(b))if(b&&"function"==typeof b.handleEvent)b=p(b.handleEvent,b);else throw Error("Invalid listener argument");this.w=2147483647<Number(a)?-1:l.setTimeout(b,a||0)};g.pb=function(a){0!=this.w||this.start(a)};
function Vc(a){0!=a.w&&l.clearTimeout(a.w);a.w=0}g.ob=function(){0!=this.w&&(Vc(this),this.Z())};g.Z=function(){this.w=0;this.a&&this.a.call(this.b)};var u={},U=null;function Wc(a){a=qa(a);delete u[a];Sa()&&U&&Vc(U)}function Xc(){U||(U=new Uc(function(){Yc()},20));var a=U;0!=a.w||a.start()}function Yc(){var a=wa();Qa(u,function(b){Zc(b,a)});Sa()||Xc()};function $c(){S.call(this);this.a=0;this.endTime=this.b=null}r($c,S);$c.prototype.l=function(a){T(this,a)};function ad(a,b,c,d){$c.call(this);if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.c=a;this.A=b;this.duration=c;this.g=d;this.coords=[];this.u=!1;this.progress=this.o=0;this.f=null}r(ad,$c);g=ad.prototype;g.Pa=function(){return this.duration};g.wa=function(a){this.u=a};g.Xb=function(){return this.u};
function bd(a){Wc(a);a.a=0;cd(a,a.progress);a.l("stop");a.l("end")}g.Eb=function(){1==this.a&&(Wc(this),this.a=-1,this.l("pause"))};g.qc=function(a){this.progress=a;1==this.a&&(this.b=wa()-this.duration*this.progress,this.endTime=this.b+this.duration)};g.i=function(){0==this.a||bd(this);this.l("destroy");ad.v.i.call(this)};g.va=function(){this.R()};
function Zc(a,b){b<a.b&&(a.endTime=b+a.endTime-a.b,a.b=b);a.progress=(b-a.b)/(a.endTime-a.b);1<a.progress&&(a.progress=1);a.o=1E3/(b-a.f);a.f=b;cd(a,a.progress);1==a.progress?(a.a=0,Wc(a),a.l("finish"),a.l("end")):1==a.a&&a.l("animate")}function cd(a,b){m(a.g)&&(b=a.g(b));a.coords=Array(a.c.length);for(var c=0;c<a.c.length;c++)a.coords[c]=(a.A[c]-a.c[c])*b+a.c[c]}g.l=function(a){T(this,new dd(a,this))};
function dd(a,b){E.call(this,a);this.coords=b.coords;this.o=b.coords[0];this.A=b.coords[1];this.u=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.g=b.o;this.m=b.a;this.a=b}r(dd,E);dd.prototype.b=function(){return Ba(this.coords,Math.round)};function ed(a,b,c,d,e,f){if(z&&!B("525"))return!0;if(A&&e)return fd(a);if(e&&!d)return!1;if(!y){"number"===typeof b&&(b=gd(b));var h=17==b||18==b||A&&91==b;if((!c||A)&&h||A&&16==b&&(d||f))return!1}if((z||x)&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(w&&d&&b==a)return!1;switch(a){case 13:return y?f||e?!1:!(c&&d):!0;case 27:return!(z||x||y)}return y&&(d||e||f)?!1:fd(a)}
function fd(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||(z||x)&&0==a)return!0;switch(a){case 32:case 43:case 63:case 64:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:case 163:case 58:return!0;case 173:return y;default:return!1}}function gd(a){if(y)a=hd(a);else if(A&&z)switch(a){case 93:a=91}return a}
function hd(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};function V(a,b){S.call(this);a&&id(this,a,b)}r(V,S);g=V.prototype;g.F=null;g.L=null;g.U=null;g.M=null;g.h=-1;g.s=-1;g.P=!1;
var jd={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},kd={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},ld=!z||B("525"),md=A&&y;g=V.prototype;
g.fa=function(a){if(z||x)if(17==this.h&&!a.ctrlKey||18==this.h&&!a.altKey||A&&91==this.h&&!a.metaKey)this.s=this.h=-1;-1==this.h&&(a.ctrlKey&&17!=a.a?this.h=17:a.altKey&&18!=a.a?this.h=18:a.metaKey&&91!=a.a&&(this.h=91));ld&&!ed(a.a,this.h,a.shiftKey,a.ctrlKey,a.altKey,a.metaKey)?this.handleEvent(a):(this.s=gd(a.a),md&&(this.P=a.altKey))};g.ga=function(a){this.s=this.h=-1;this.P=a.altKey};
g.handleEvent=function(a){var b=a.b,c=b.altKey;if(w&&"keypress"==a.type){var d=this.s;var e=13!=d&&27!=d?b.keyCode:0}else(z||x)&&"keypress"==a.type?(d=this.s,e=0<=b.charCode&&63232>b.charCode&&fd(d)?b.charCode:0):kb&&!z?(d=this.s,e=fd(d)?b.keyCode:0):("keypress"==a.type?(md&&(c=this.P),b.keyCode==b.charCode?32>b.keyCode?(d=b.keyCode,e=0):(d=this.s,e=b.charCode):(d=b.keyCode||this.s,e=b.charCode||0)):(d=b.keyCode||this.s,e=b.charCode||0),A&&63==e&&224==d&&(d=191));var f=d=gd(d);d?63232<=d&&d in jd?
f=jd[d]:25==d&&a.shiftKey&&(f=9):b.keyIdentifier&&b.keyIdentifier in kd&&(f=kd[b.keyIdentifier]);y&&ld&&"keypress"==a.type&&!ed(f,this.h,a.shiftKey,a.ctrlKey,c,a.metaKey)||(a=f==this.h,this.h=f,b=new nd(f,e,a,b),b.altKey=c,T(this,b))};g.Db=function(){return this.F};function id(a,b,c){a.M&&od(a);a.F=b;a.L=I(a.F,"keypress",a,c);a.U=I(a.F,"keydown",a.fa,c,a);a.M=I(a.F,"keyup",a.ga,c,a)}function od(a){a.L&&(K(a.L),K(a.U),K(a.M),a.L=null,a.U=null,a.M=null);a.F=null;a.h=-1;a.s=-1}
g.i=function(){V.v.i.call(this);od(this)};function nd(a,b,c,d){F.call(this,d);this.type="key";this.a=a;this.g=b;this.repeat=c}r(nd,F);function W(a,b,c,d,e,f){function h(q){q&&(q.tabIndex=0,Kc(q,k.ba),Q(q,"goog-zippy-header"),pd(k,q),qd(k,q))}S.call(this);this.N=e||ec();this.c=this.N.I(a)||null;this.g=this.N.I(d||null);this.A=m(b)?b:null;this.ba=f||"tab";this.f=this.A||!b?null:this.N.I(b);this.b=1==c;void 0!==c||this.A||(this.g?this.b="none"!=this.g.style.display:this.c&&(this.b=Nc(this.c,"goog-zippy-expanded")));this.V=new R(this);this.u=new V;this.W=new R(this);var k=this;h(this.c);h(this.g);this.C(this.b)}r(W,S);g=W.prototype;
g.T=!0;g.S=!0;g.i=function(){W.v.i.call(this);xb(this.V);xb(this.u);xb(this.W)};g.nb=function(){var a=this.g;return a&&"none"!=a.style.display?a:this.c};g.C=function(a){this.f?this.f.style.display=a?"":"none":a&&this.A&&(this.f=this.A());this.f&&Q(this.f,"goog-zippy-content");this.g?(this.c.style.display=a?"none":"",this.g.style.display=a?"":"none"):rd(this,a);this.b=a;T(this,new X("toggle",this,this.b))};
function rd(a,b){if(a.c){var c=a.c;b?Q(c,"goog-zippy-expanded"):Oc(c,"goog-zippy-expanded");c=a.c;b?Oc(c,"goog-zippy-collapsed"):Q(c,"goog-zippy-collapsed");a=a.c;Array.isArray(b)&&(b=b.join(" "));""===b||void 0==b?(Yb||(Yb={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",busy:!1,disabled:!1,hidden:!1,invalid:"false"}),b=Yb,"expanded"in b?a.setAttribute("aria-expanded",
b.expanded):a.removeAttribute("aria-expanded")):a.setAttribute("aria-expanded",b)}}g.Tb=function(){return this.S};g.Ub=function(){return this.T};g.nc=function(a){this.S!=a&&((this.S=a)?(qd(this,this.c),qd(this,this.g)):(Sc(this.V),od(this.u)))};g.oc=function(a){this.T!=a&&((this.T=a)?(pd(this,this.c),pd(this,this.g)):Sc(this.W))};function qd(a,b){b&&(id(a.u,b),a.V.B(a.u,"key",a.na))}function pd(a,b){b&&a.W.B(b,"click",a.ma)}
g.na=function(a){if(13==a.a||32==a.a)this.C(!this.b),T(this,new X("action",this,this.b,a)),a.preventDefault(),a.stopPropagation()};g.ma=function(a){this.C(!this.b);T(this,new X("action",this,this.b,a))};function X(a,b,c,d){E.call(this,a,b);this.a=c;this.b=d||null}r(X,E);function Y(a,b,c,d,e){d=d||ec();var f=d.X("DIV",{style:"overflow:hidden"});b=d.I(b);b.parentNode.replaceChild(f,b);f.appendChild(b);this.o=f;this.a=null;W.call(this,a,b,c,void 0,d,e);a=this.b;this.o.style.display=a?"":"none";rd(this,a)}r(Y,W);g=Y.prototype;g.Jb=500;g.da=function(a){return 1-Math.pow(1-a,3)};g.Nb=function(){return null!=this.a};
g.C=function(a){if(this.b!=a||this.a){"none"==this.o.style.display&&(this.o.style.display="");var b=this.f.offsetHeight;if(this.a){Tb(this.a);bd(this.a);var c=b-Math.abs(parseInt(this.f.style.marginTop,10))}else c=a?0:b;rd(this,a);this.a=new ad([0,c],[0,a?b:0],500,this.da);I(this.a,["begin","animate","end"],this.ja,!1,this);I(this.a,"begin",p(this.ka,this,a));I(this.a,"end",p(this.la,this,a));a:{a=this.a;if(0==a.a)a.progress=0,a.coords=a.c;else if(1==a.a)break a;Wc(a);b=wa();a.b=b;-1==a.a&&(a.b-=
a.duration*a.progress);a.endTime=a.b+a.duration;a.f=a.b;a.progress||a.l("begin");a.l("play");-1==a.a&&a.l("resume");a.a=1;c=qa(a);c in u||(u[c]=a);Xc();Zc(a,b)}}};g.ja=function(a){var b=this.f;b.style.marginTop=a.A-b.offsetHeight+"px"};g.ka=function(a){T(this,new X("a",this,a))};g.la=function(a){a&&(this.f.style.marginTop="0");Tb(this.a);this.b=a;this.a=null;a||(this.o.style.display="none");T(this,new X("toggle",this,a));T(this,new X("b",this,a))};function Z(){var a=L.call(this)||this;a.a=new R;return a}la(Z,L);Z.prototype.connectedCallback=function(){var a=this.querySelector(".devsite-tracking-question");a&&sd(this,a)};Z.prototype.disconnectedCallback=function(){Sc(this.a)};
function sd(a,b){Q(b.children[0],"devsite-tracking-question-text");for(var c=1;c<b.children.length;c++){var d=b.children[c].children[0];Q(d,"devsite-tracking-question-choice-button");Q(b.children[c].children[1],"devsite-tracking-question-hidden");Kc(d,"button")}a.a.B(a,"click",function(e){if(Nc(e.target,"devsite-tracking-question-choice-button")&&(e.preventDefault(),e.stopPropagation(),e=e.target)){var f=e.parentNode;if(f){if((e=f.parentNode)&&e.children.length){(new Y(null,e.children[0],!0)).C(!1);
for(var h=1;h<e.children.length;h++)(new Y(null,e.children[h].children[0],!0)).C(!1);1<f.children.length&&(h=f.children[1],e.appendChild(h),Oc(h,"devsite-tracking-question-hidden"),(new Y(null,h,!1)).C(!0))}f=f.getAttribute("data-item-name");if(e){var k=e.getAttribute("data-tracking-dimension");var q=e.getAttribute("data-tracking-gaid")}null!==f&&null!==k&&null!==q&&(a.dispatchEvent(new CustomEvent("devsite-analytics-set-dimension",{detail:{name:k,value:f,gaid:q},bubbles:!0})),a.dispatchEvent(new CustomEvent("devsite-analytics-observation",
{detail:{category:"Tracking Question",action:"click",label:f},bubbles:!0})))}}})}Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-tracking-question",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteTrackingQuestion",a)};}).call(this);
