(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f,h="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var l=ba(this);function m(a,b){if(b){var c=l;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}var n;
if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var p;a:{var ca={s:!0},q={};try{q.__proto__=ca;p=q.s;break a}catch(a){}p=!1}n=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=n;
function t(a,b){a.prototype=h(b.prototype);a.prototype.constructor=a;if(r)r(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.X=b.prototype}m("Object.setPrototypeOf",function(a){return a||r});
var da=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=h(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();m("Reflect.construct",function(){return da});var u=this||self;
function ea(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function v(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length}var fa=Date.now||function(){return+new Date};var ha=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(ha&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function w(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}t(w,HTMLElement);w.prototype.f=function(){console.warn(this.tagName,"has not implemented update")};w.prototype.b=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
w.prototype.c=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};var x=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},y=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)};
function z(a){return Array.prototype.concat.apply([],arguments)}function ia(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var A;a:{var B=u.navigator;if(B){var C=B.userAgent;if(C){A=C;break a}}A=""};function ja(a){return String(a).replace(/\-([a-z])/g,function(b,c){return c.toUpperCase()})}function ka(a){return a.replace(/(^|[\s]+)([a-z])/g,function(b,c,d){return c+d.toUpperCase()})};var la=-1!=A.indexOf("Opera"),ma=-1!=A.indexOf("Trident")||-1!=A.indexOf("MSIE"),na=-1!=A.indexOf("Gecko")&&!(-1!=A.toLowerCase().indexOf("webkit")&&-1==A.indexOf("Edge"))&&!(-1!=A.indexOf("Trident")||-1!=A.indexOf("MSIE"))&&-1==A.indexOf("Edge"),oa=-1!=A.toLowerCase().indexOf("webkit")&&-1==A.indexOf("Edge");function D(a,b,c){var d=E[c];if(!d){var e=ja(c);d=e;void 0===a.style[e]&&(e=(oa?"Webkit":na?"Moz":ma?"ms":la?"O":null)+ka(e),void 0!==a.style[e]&&(d=e));E[c]=d}(c=d)&&(a.style[c]=b)}var E={};var F="StopIteration"in u?u.StopIteration:{message:"StopIteration",stack:""};function G(){}G.prototype.a=function(){throw F;};G.prototype.b=function(){return this};function H(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof H)for(c=a.h(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}f=H.prototype;f.g=function(){I(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};f.h=function(){I(this);return this.a.concat()};
f.O=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(K(this.b,c)&&this.b[c]==a)return!0}return!1};f.u=function(a,b){if(this===a)return!0;if(this.c!=a.c)return!1;b=b||pa;I(this);for(var c,d=0;c=this.a[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function pa(a,b){return a===b}f.P=function(){return 0==this.c};f.N=function(){this.b={};this.f=this.c=this.a.length=0};
function I(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];K(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],K(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}f.get=function(a,b){return K(this.b,a)?this.b[a]:b};f.set=function(a,b){K(this.b,a)||(this.c++,this.a.push(a),this.f++);this.b[a]=b};f.forEach=function(a,b){for(var c=this.h(),d=0;d<c.length;d++){var e=c[d],g=this.get(e);a.call(b,g,e,this)}};
f.Z=function(){for(var a=new H,b=0;b<this.a.length;b++){var c=this.a[b];a.set(this.b[c],c)}return a};f.Y=function(){I(this);for(var a={},b=0;b<this.a.length;b++){var c=this.a[b];a[c]=this.b[c]}return a};f.A=function(){return L(this,!0)};f.D=function(){return L(this,!1)};function L(a,b){I(a);var c=0,d=a.f,e=new G;e.a=function(){if(d!=a.f)throw Error("The map has changed since the iterator was created");if(c>=a.a.length)throw F;var g=a.a[c++];return b?g:a.b[g]};return e}
function K(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function qa(a){if(a.g&&"function"==typeof a.g)return a.g();if("string"===typeof a)return a.split("");if(v(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function ra(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(v(a)||"string"===typeof a)y(a,b,c);else{if(a.h&&"function"==typeof a.h)var d=a.h();else if(a.g&&"function"==typeof a.g)d=void 0;else if(v(a)||"string"===typeof a){d=[];for(var e=a.length,g=0;g<e;g++)d.push(g)}else for(g in d=[],e=0,a)d[e++]=g;e=qa(a);g=e.length;for(var k=0;k<g;k++)b.call(c,e[k],d&&d[k],a)}};var sa=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function ta(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var g=a[c].substring(0,d);e=a[c].substring(d+1)}else g=a[c];b(g,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function M(a){this.b=this.m=this.j="";this.f=null;this.l=this.c="";this.i=this.o=!1;if(a instanceof M){this.i=a.i;N(this,a.j);var b=a.m;O(this);this.m=b;b=a.b;O(this);this.b=b;P(this,a.f);b=a.c;O(this);this.c=b;Q(this,R(a.a));a=a.l;O(this);this.l=a}else a&&(b=String(a).match(sa))?(this.i=!1,N(this,b[1]||"",!0),a=b[2]||"",O(this),this.m=S(a),a=b[3]||"",O(this),this.b=S(a,!0),P(this,b[4]),a=b[5]||"",O(this),this.c=S(a,!0),Q(this,b[6]||"",!0),a=b[7]||"",O(this),this.l=S(a)):(this.i=!1,this.a=new T(null,
this.i))}f=M.prototype;f.toString=function(){var a=[],b=this.j;b&&a.push(U(b,V,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.m)&&a.push(U(b,V,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.f,null!=c&&a.push(":",String(c));if(c=this.c)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(U(c,"/"==c.charAt(0)?ua:va,!0));(c=this.a.toString())&&a.push("?",c);(c=this.l)&&a.push("#",U(c,wa));return a.join("")};
f.L=function(a){var b=new M(this),c=!!a.j;c?N(b,a.j):c=!!a.m;if(c){var d=a.m;O(b);b.m=d}else c=!!a.b;c?(d=a.b,O(b),b.b=d):c=null!=a.f;d=a.c;if(c)P(b,a.f);else if(c=!!a.c){if("/"!=d.charAt(0))if(this.b&&!this.c)d="/"+d;else{var e=b.c.lastIndexOf("/");-1!=e&&(d=b.c.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var g=[],k=0;k<e.length;){var J=e[k++];"."==J?d&&k==e.length&&g.push(""):".."==J?((1<g.length||1==
g.length&&""!=g[0])&&g.pop(),d&&k==e.length&&g.push("")):(g.push(J),d=!0)}d=g.join("/")}else d=e}c?(O(b),b.c=d):c=""!==a.a.toString();c?Q(b,R(a.a)):c=!!a.l;c&&(a=a.l,O(b),b.l=a);return b};function N(a,b,c){O(a);a.j=c?S(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))}function P(a,b){O(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.f=b}else a.f=null}function Q(a,b,c){O(a);b instanceof T?(a.a=b,xa(a.a,a.i)):(c||(b=U(b,ya)),a.a=new T(b,a.i));return a}
f.V=function(a,b){return Q(this,a,b)};f.w=function(){return S(this.a.toString())};f.U=function(a,b){O(this);Array.isArray(b)||(b=[String(b)]);za(this.a,a,b);return this};f.C=function(a){return this.a.g(a)};f.B=function(a){return this.a.get(a)};f.R=function(a){return(!this.b&&!a.b||this.b==a.b)&&(null==this.f&&null==a.f||this.f==a.f)};
f.T=function(){O(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^fa()).toString(36);O(this);this.a.set("zx",a);return this};f.K=function(a){O(this);W(this.a,a);return this};f.W=function(a){this.o=a;return this};f.S=function(){return this.o};function O(a){if(a.o)throw Error("Tried to modify a read-only Uri");}f.M=function(a){this.i=a;this.a&&xa(this.a,a);return this};
function S(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function U(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Aa),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function Aa(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var V=/[#\/\?@]/g,va=/[#\?:]/g,ua=/[#\?]/g,ya=/[#\?@]/g,wa=/#/g;function T(a,b){this.b=this.a=null;this.c=a||null;this.f=!!b}
function X(a){a.a||(a.a=new H,a.b=0,a.c&&ta(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}f=T.prototype;f.I=function(){X(this);return this.b};f.add=function(a,b){X(this);this.c=null;a=Y(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};function W(a,b){X(a);b=Y(a,b);K(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,K(a.b,b)&&(delete a.b[b],a.c--,a.f++,a.a.length>2*a.c&&I(a)))}f.F=function(){this.a=this.c=null;this.b=0};
f.J=function(){X(this);return 0==this.b};function Ba(a,b){X(a);b=Y(a,b);return K(a.a.b,b)}f.G=function(a){var b=this.g();return 0<=x(b,a)};f.forEach=function(a,b){X(this);this.a.forEach(function(c,d){y(c,function(e){a.call(b,e,d,this)},this)},this)};f.h=function(){X(this);for(var a=this.a.g(),b=this.a.h(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};
f.g=function(a){X(this);var b=[];if("string"===typeof a)Ba(this,a)&&(b=z(b,this.a.get(Y(this,a))));else{a=this.a.g();for(var c=0;c<a.length;c++)b=z(b,a[c])}return b};f.set=function(a,b){X(this);this.c=null;a=Y(this,a);Ba(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};f.get=function(a,b){if(!a)return b;a=this.g(a);return 0<a.length?String(a[0]):b};function za(a,b,c){W(a,b);0<c.length&&(a.c=null,a.a.set(Y(a,b),ia(c)),a.b+=c.length)}
f.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.h(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.g(d);for(var g=0;g<d.length;g++){var k=e;""!==d[g]&&(k+="="+encodeURIComponent(String(d[g])));a.push(k)}}return this.c=a.join("&")};f.v=function(a){X(this);this.a.forEach(function(b,c){0<=x(a,c)||W(this,c)},this);return this};function R(a){var b=new T;b.c=a.c;a.a&&(b.a=new H(a.a),b.b=a.b);return b}
function Y(a,b){b=String(b);a.f&&(b=b.toLowerCase());return b}function xa(a,b){b&&!a.f&&(X(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(W(this,d),za(this,e,c))},a));a.f=b}f.H=function(a){for(var b=0;b<arguments.length;b++)ra(arguments[b],function(c,d){this.add(d,c)},this)};function Z(){var a=w.call(this)||this;a.a=!1;return a}t(Z,w);Z.prototype.connectedCallback=function(){Ca(this)};
function Ca(a){if(!a.a){var b=a.querySelector("iframe");if(b){var c=b.classList.contains("inherit-locale");b.classList.remove("framebox");b.classList.remove("inherit-locale");b.removeAttribute("style");b.removeAttribute("is-upgraded");var d=b.dataset.src||b.src;if(d){d=new URL(d,document.location.origin);var e=new M(d.href),g=DevsiteApp.getLocale();g&&c&&(O(e),e.a.set("hl",g));d.search=e.a.toString();b.removeAttribute("data-src");b.src!==d.href&&b.setAttribute("src",d.href)}["height","width"].forEach(function(k){b.hasAttribute(k)&&
(a.setAttribute(k,b.getAttribute(k)),b.removeAttribute(k))});a.className=b.className;b.removeAttribute("class");a.a=!0}else console.warn("devsite-iframe is missing an iframe")}}Z.prototype.attributeChangedCallback=function(a,b,c){if("height"===a||"width"===a)if("string"===typeof a)D(this,c||"",a);else for(var d in a)D(this,a[d],d)};l.Object.defineProperties(Z,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["height","width"]}}});Z.prototype.attributeChangedCallback=Z.prototype.attributeChangedCallback;
Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-iframe",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteIframe",a)};}).call(this);
