(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},g="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function h(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var k=h(this);function l(a,b){if(b){var c=k;a=a.split(".");for(var e=0;e<a.length-1;e++){var d=a[e];d in c||(c[d]={});c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&g(c,a,{configurable:!0,writable:!0,value:b})}}var m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var r={s:!0},t={};try{t.__proto__=r;n=t.s;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var u=m;
function v(a,b){a.prototype=f(b.prototype);a.prototype.constructor=a;if(u)u(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c];a.A=b.prototype}
l("String.prototype.startsWith",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var e=this.length,d=b.length;c=Math.max(0,Math.min(c|0,this.length));for(var p=0;p<d&&c<e;)if(this[c++]!=b[p++])return!1;return p>=d}});l("Object.setPrototypeOf",function(a){return a||u});
var w=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,e,d){c=b(c,e);d&&Reflect.setPrototypeOf(c,d.prototype);return c}}return function(c,e,d){void 0===d&&(d=c);d=f(d.prototype||Object.prototype);return Function.prototype.apply.call(c,d,e)||d}}();l("Reflect.construct",function(){return w});var x=this||self;
function y(a,b){function c(){}c.prototype=b.prototype;a.A=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.B=function(e,d,p){for(var E=Array(arguments.length-2),q=2;q<arguments.length;q++)E[q-2]=arguments[q];return b.prototype[d].apply(e,E)}};function z(a,b){if(b)a=a.replace(A,"&amp;").replace(B,"&lt;").replace(C,"&gt;").replace(D,"&quot;").replace(F,"&#39;").replace(G,"&#0;");else{if(!aa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(A,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(B,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(C,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(D,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(F,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(G,"&#0;"))}return a}var A=/&/g,B=/</g,C=/>/g,D=/"/g,F=/'/g,G=/\x00/g,aa=/[\x00&<>"']/;function H(a){this.a=I===I&&a||"";this.c=ba}H.prototype.g=!0;H.prototype.b=function(){return this.a.toString()};H.prototype.l=!0;H.prototype.j=function(){return 1};var ba={},I={};function J(){this.w="";this.o=K}J.prototype.g=!0;var K={};J.prototype.b=function(){return""};function L(){this.v="";this.m=M}L.prototype.g=!0;var M={};L.prototype.b=function(){return""};function N(){this.a="";this.u=O;this.c=null}N.prototype.l=!0;N.prototype.j=function(){return this.c};N.prototype.g=!0;N.prototype.b=function(){return this.a.toString()};function P(a){return a instanceof N&&a.constructor===N&&a.u===O?a.a:"type_error:SafeHtml"}function Q(a){if(a instanceof N)return a;var b="object"==typeof a,c=null;b&&a.l&&(c=a.j());a=z(b&&a.g?a.b():String(a));return R(a,c)}var O={};function R(a,b){var c=new N;c.a=a;c.c=b;return c}var S=new N;
S.a=x.trustedTypes&&x.trustedTypes.emptyHTML?x.trustedTypes.emptyHTML:"";S.c=0;var ca=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=P(S);return!b.parentElement});var T={},da={},ea={};function U(){throw Error("Do not instantiate directly");}U.prototype.i=null;U.prototype.toString=function(){return this.h};U.prototype.b=function(){if(this.f!==da)throw Error("Sanitized content was not of kind URI.");return new H(this.toString())};function V(){U.call(this)}y(V,U);V.prototype.f=T;var fa=function(a){function b(c){this.h=c}b.prototype=a.prototype;return function(c,e){c=new b(String(c));void 0!==e&&(c.i=e);return c}}(V);function W(a){return a.replace(/<\//g,"<\\/").replace(/\]\]>/g,"]]\\>")}function X(a){null!=a&&a.f===T?a=String(String(a.h).replace(ha,"").replace(ia,"&lt;")).replace(ja,ka):(a=String(a),a=z(a,void 0));return a}
var la={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function ka(a){return la[a]}
var ja=/[\x00\x22\x27\x3c\x3e]/g,ma=/^(?!-*(?:expression|(?:moz-)?binding))(?:(?:[.#]?-?(?:[_a-z0-9-]+)(?:-[_a-z0-9-]+)*-?|(?:rgb|hsl)a?\([0-9.%,\u0020]+\)|-?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[a-z]{1,4}|%)?|!important)(?:\s*[,\u0020]\s*|$))*$/i,ha=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,ia=/</g;var na=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(na&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function Y(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}v(Y,HTMLElement);Y.prototype.c=function(){console.warn(this.tagName,"has not implemented update")};Y.prototype.b=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
Y.prototype.a=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function Z(){return Y.apply(this,arguments)||this}v(Z,Y);
Z.prototype.connectedCallback=function(){var a;if(this.hasAttribute("single-color")){var b=this.getAttribute("single-color");b&&b.startsWith("#")&&(a=b)}var c="";for(b=0;4>b;b++){var e='<div class="devsite-spinner__layer devsite-spinner__layer-'+X(1+b)+'"';if(a){if(null!=a&&a.f===ea)var d=W(a.h);else null==a?d="":a instanceof J?d=W(a instanceof J&&a.constructor===J&&a.o===K?a.w:"type_error:SafeStyle"):a instanceof L?d=W(a instanceof L&&a.constructor===L&&a.m===M?a.v:"type_error:SafeStyleSheet"):(d=
String(a),d=ma.test(d)?d:"zSoyz");d=' style="border-color: '+X(d)+';"'}else d="";c+=e+d+'><div class="devsite-spinner__circle-clipper devsite-spinner__left"><div class="devsite-spinner__circle"></div></div><div class="devsite-spinner__gap-patch"><div class="devsite-spinner__circle"></div></div><div class="devsite-spinner__circle-clipper devsite-spinner__right"><div class="devsite-spinner__circle"></div></div></div>'}a=fa(c);b=typeof a;if("object"==b&&null!=a||"function"==b)if(a instanceof U){if(a.f!==
T)throw Error("Sanitized content was not of kind HTML.");a=R(a.toString(),a.i||null)}else a=Q("zSoyz");else a=Q(String(a));if(ca())for(;this.lastChild;)this.removeChild(this.lastChild);this.innerHTML=P(a);if(a=this.getAttribute("size"))this.style.width=a+"px",this.style.height=a+"px"};Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-spinner",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteSpinner",a)};}).call(this);
