(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var k,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function m(a,b){if(b){var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}var n;
if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var r;a:{var ea={F:!0},fa={};try{fa.__proto__=ea;r=fa.F;break a}catch(a){}r=!1}n=r?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var t=n;
function ha(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(t)t(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.l=b.prototype}m("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});
m("String.prototype.startsWith",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var d=this.length,e=b.length;c=Math.max(0,Math.min(c|0,this.length));for(var f=0;f<e&&c<d;)if(this[c++]!=b[f++])return!1;return f>=e}});
m("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});m("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});m("Object.setPrototypeOf",function(a){return a||t});
var ia=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=aa(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();m("Reflect.construct",function(){return ia});
m("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});var u=this||self;function v(){}
function ja(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function w(a){var b=ja(a);return"array"==b||"object"==b&&"number"==typeof a.length}function x(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ka(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}
function z(a,b){function c(){}c.prototype=b.prototype;a.l=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.J=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}};var la=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ma=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
function na(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var pa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function A(a,b){return a<b?-1:a>b?1:0};var B;a:{var qa=u.navigator;if(qa){var ra=qa.userAgent;if(ra){B=ra;break a}}B=""};function sa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function ta(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};function C(a,b){this.a=a===ua&&b||"";this.b=va}C.prototype.g=!0;C.prototype.c=function(){return this.a.toString()};C.prototype.v=!0;C.prototype.u=function(){return 1};var wa=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,va={},ua={};function xa(a,b){b instanceof C||b instanceof C||(b="object"==typeof b&&b.g?b.c():String(b),wa.test(b)||(b="about:invalid#zClosurez"),b=new C(ua,b));b=b instanceof C&&b.constructor===C&&b.b===va?b.a:"type_error:SafeUrl";a.href=b};function D(a){D[" "](a);return a}D[" "]=v;function ya(a,b){var c=za;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Aa=-1!=B.indexOf("Opera"),E=-1!=B.indexOf("Trident")||-1!=B.indexOf("MSIE"),Ba=-1!=B.indexOf("Edge"),Ca=-1!=B.indexOf("Gecko")&&!(-1!=B.toLowerCase().indexOf("webkit")&&-1==B.indexOf("Edge"))&&!(-1!=B.indexOf("Trident")||-1!=B.indexOf("MSIE"))&&-1==B.indexOf("Edge"),F=-1!=B.toLowerCase().indexOf("webkit")&&-1==B.indexOf("Edge"),Da=-1!=B.indexOf("Macintosh");function Ea(){var a=u.document;return a?a.documentMode:void 0}var H;
a:{var I="",J=function(){var a=B;if(Ca)return/rv:([^\);]+)(\)|;)/.exec(a);if(Ba)return/Edge\/([\d\.]+)/.exec(a);if(E)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(F)return/WebKit\/(\S+)/.exec(a);if(Aa)return/(?:Version)[ \/]?(\S+)/.exec(a)}();J&&(I=J?J[1]:"");if(E){var K=Ea();if(null!=K&&K>parseFloat(I)){H=String(K);break a}}H=I}var Fa=H,za={};
function Ga(a){return ya(a,function(){for(var b=0,c=pa(String(Fa)).split("."),d=pa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==g[0].length&&0==h[0].length)break;b=A(0==g[1].length?0:parseInt(g[1],10),0==h[1].length?0:parseInt(h[1],10))||A(0==g[2].length,0==h[2].length)||A(g[2],h[2]);g=g[3];h=h[3]}while(0==b)}return 0<=b})}var Ha;
if(u.document&&E){var Ia=Ea();Ha=Ia?Ia:parseInt(Fa,10)||void 0}else Ha=void 0;var Ja=Ha;function L(a,b){this.a=void 0!==a?a:0;this.b=void 0!==b?b:0}k=L.prototype;k.T=function(){return new L(this.a,this.b)};k.K=function(a){return a instanceof L&&(this==a?!0:this&&a?this.a==a.a&&this.b==a.b:!1)};k.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);return this};k.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);return this};k.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);return this};
k.V=function(a,b){a instanceof L?(this.a+=a.a,this.b+=a.b):(this.a+=Number(a),"number"===typeof b&&(this.b+=b));return this};k.U=function(a,b){this.a*=a;this.b*="number"===typeof b?b:a;return this};k.ca=function(a,b){a=a*Math.PI/180;b=b||new L(0,0);var c=this.a,d=this.b,e=Math.cos(a);a=Math.sin(a);this.a=(c-b.a)*e-(d-b.b)*a+b.a;this.b=(c-b.a)*a+(d-b.b)*e+b.b};function Ka(){var a=document,b=a.scrollingElement?a.scrollingElement:F||"CSS1Compat"!=a.compatMode?a.body||a.documentElement:a.documentElement;a=a.parentWindow||a.defaultView;return E&&Ga("10")&&a.pageYOffset!=b.scrollTop?new L(b.scrollLeft,b.scrollTop):new L(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)}function M(a){a&&a.parentNode&&a.parentNode.removeChild(a)};var N="StopIteration"in u?u.StopIteration:{message:"StopIteration",stack:""};function O(){}O.prototype.next=function(){throw N;};O.prototype.h=function(){return this};function La(a){if(a instanceof O)return a;if("function"==typeof a.h)return a.h(!1);if(w(a)){var b=0,c=new O;c.next=function(){for(;;){if(b>=a.length)throw N;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");}
function Ma(a,b){if(w(a))try{ma(a,b,void 0)}catch(c){if(c!==N)throw c;}else{a=La(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==N)throw c;}}}function Na(a){if(w(a))return na(a);a=La(a);var b=[];Ma(a,function(c){b.push(c)});return b};function Oa(a){var b=void 0===b?!0:b;var c={path:a},d=window.history.state;d&&(c.previousPath=d.previousPath);d=Ka();c.scrollX=d.a;c.scrollY=d.b;window.history.replaceState(c,document.title,a);b&&document.body.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))}function Pa(a){return(void 0===a?"":a).toLowerCase().trim().replace(/\s+/g,"-").replace(/[!@#\$%\^&\*\(\)\{\}<>\?\\\/'"]+/g,"").trim()};var Qa=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(Qa&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function P(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ha(P,HTMLElement);P.prototype.D=function(){console.warn(this.tagName,"has not implemented update")};P.prototype.u=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
P.prototype.C=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function Q(){this.f=this.f;this.b=this.b}k=Q.prototype;k.f=!1;k.I=function(){return this.f};k.L=Q.prototype.I;k.w=function(){this.f||(this.f=!0,this.o())};k.ba=function(a){a=ka(Ra,a);this.f?a():(this.b||(this.b=[]),this.b.push(a))};k.o=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function Ra(a){a&&"function"==typeof a.w&&a.w()};var Sa=!E||9<=Number(Ja),Ta=!E||9<=Number(Ja),Wa=E&&!Ga("9"),Xa=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{u.addEventListener("test",v,b),u.removeEventListener("test",v,b)}catch(c){}return a}();function R(a,b){this.type=a;this.b=this.target=b;this.A=this.c=!1}R.prototype.s=function(){this.c=!0};R.prototype.j=function(){this.A=!0};function S(a,b){R.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.B=this.v=0;this.key="";this.g=this.u=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.C=null;this.D=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(Ca){a:{try{D(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.v=F||void 0!==a.offsetX?a.offsetX:a.layerX,this.B=F||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.u=a.keyCode||0;this.key=a.key||"";this.g=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.D=Da?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Ya[a.pointerType]||"";this.C=a.state;this.a=a;a.defaultPrevented&&this.j()}}z(S,R);var Za=[1,4,2],Ya={2:"touch",3:"pen",4:"mouse"};
S.prototype.da=function(){return(Sa?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Za[0]))&&!(F&&Da&&this.ctrlKey)};S.prototype.s=function(){S.l.s.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};S.prototype.j=function(){S.l.j.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Wa)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};S.prototype.aa=function(){return this.a};var T="closure_listenable_"+(1E6*Math.random()|0),$a=0;function ab(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++$a;this.i=this.m=!1}function U(a){a.i=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function bb(a){this.src=a;this.a={};this.b=0}k=bb.prototype;k.P=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};k.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=cb(a,b,d,e);-1<g?(b=a[g],c||(b.m=!1)):(b=new ab(b,this.src,f,!!d,e),b.m=c,a.push(b));return b};
k.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=cb(e,b,c,d);return-1<b?(U(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};k.S=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,U(d[e]);delete this.a[c];this.b--}return b};k.M=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
k.R=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return ta(this.a,function(f){for(var g=0;g<f.length;++g)if(!(c&&f[g].type!=d||e&&f[g].capture!=b))return!0;return!1})};function cb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.i&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var db="closure_lm_"+(1E6*Math.random()|0),eb={},fb=0;function gb(a,b,c,d,e){if(d&&d.once)return hb(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)gb(a,b[f],c,d,e);return null}c=ib(c);return a&&a[T]?V(a,b,c,x(d)?!!d.capture:!!d,e):jb(a,b,c,!1,d,e)}
function jb(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=x(e)?!!e.capture:!!e,h=W(a);h||(a[db]=h=new bb(a));c=h.add(b,c,d,g,f);if(c.a)return c;d=kb();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Xa||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(lb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");fb++;return c}
function kb(){var a=mb,b=Ta?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function hb(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)hb(a,b[f],c,d,e);return null}c=ib(c);return a&&a[T]?a.B(b,c,x(d)?!!d.capture:!!d,e):jb(a,b,c,!0,d,e)}
function nb(a){if("number"!==typeof a&&a&&!a.i){var b=a.src;if(b&&b[T])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(lb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);fb--;if(c=W(b)){d=a.type;if(d in c.a){var e=c.a[d],f=la(e,a),g;(g=0<=f)&&Array.prototype.splice.call(e,f,1);g&&(U(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[db]=null)}else U(a)}}}
function lb(a){return a in eb?eb[a]:eb[a]="on"+a}function ob(a,b,c,d){var e=!0;if(a=W(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.i&&(f=pb(f,d),e=e&&!1!==f)}return e}function pb(a,b){var c=a.listener,d=a.b||a.src;a.m&&nb(a);return c.call(d,b)}
function mb(a,b){if(a.i)return!0;if(!Ta){if(!b)a:{b=["window","event"];for(var c=u,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new S(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.c&&0<=e;e--){b.b=d[e];var f=ob(d[e],a,!0,b);c=c&&f}for(e=0;!b.c&&e<d.length;e++)b.b=d[e],f=ob(d[e],a,!1,b),c=
c&&f}return c}return pb(a,new S(b,this))}function W(a){a=a[db];return a instanceof bb?a:null}var qb="__closure_events_fn_"+(1E9*Math.random()>>>0);function ib(a){if("function"==ja(a))return a;a[qb]||(a[qb]=function(b){return a.handleEvent(b)});return a[qb]};function X(a){Q.call(this);this.c=a;this.a={}}z(X,Q);var rb=[];function sb(a,b,c){V(a,b,"click",c,void 0)}k=X.prototype;k.Y=function(a,b,c,d,e){return V(this,a,b,c,d,e)};function V(a,b,c,d,e,f){Array.isArray(c)||(c&&(rb[0]=c.toString()),c=rb);for(var g=0;g<c.length;g++){var h=gb(b,c[g],d||a.handleEvent,e||!1,f||a.c||a);if(!h)break;a.a[h.key]=h}return a}k.O=function(a,b,c,d){return tb(this,a,b,c,d)};k.X=function(a,b,c,d,e){return tb(this,a,b,c,d,e)};
function tb(a,b,c,d,e,f){if(Array.isArray(c))for(var g=0;g<c.length;g++)tb(a,b,c[g],d,e,f);else{b=hb(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}k.Z=function(a,b,c,d){V(b,a,c,d,this.c||this);return this};k.$=function(a,b,c,d,e){V(b,a,c,d,e||this.c||this);return this};k.N=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function ub(a,b,c,d,e,f){if(Array.isArray(c))for(var g=0;g<c.length;g++)ub(a,b,c[g],d,e,f);else d=d||a.handleEvent,e=x(e)?!!e.capture:!!e,f=f||a.c||a,d=ib(d),e=!!e,b&&b[T]?c=b.v(c,d,e,f):b?(b=W(b))?(c=b.a[c.toString()],b=-1,c&&(b=cb(c,d,e,f)),c=-1<b?c[b]:null):c=null:c=null,c&&(nb(c),delete a.a[c.key])}k.ea=function(a,b,c,d,e){ub(b,a,c,d,e||this.c||this,this);return this};function vb(a){sa(a.a,function(b,c){this.a.hasOwnProperty(c)&&nb(b)},a);a.a={}}k.o=function(){X.l.o.call(this);vb(this)};
k.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function wb(){};function Y(){}z(Y,wb);Y.prototype.G=function(){var a=0;Ma(this.h(!0),function(){a++});return a};Y.prototype.H=function(){var a=Na(this.h(!0)),b=this;ma(a,function(c){b.remove(c)})};function xb(a){this.a=a}z(xb,Y);k=xb.prototype;k.W=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};k.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};k.get=function(a){a=this.a.getItem(a);if("string"!==typeof a&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};k.remove=function(a){this.a.removeItem(a)};
k.G=function(){return this.a.length};k.h=function(a){var b=0,c=this.a,d=new O;d.next=function(){if(b>=c.length)throw N;var e=c.key(b++);if(a)return e;e=c.getItem(e);if("string"!==typeof e)throw"Storage mechanism: Invalid value was encountered";return e};return d};k.H=function(){this.a.clear()};k.key=function(a){return this.a.key(a)};function yb(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a}z(yb,xb);function Z(){var a=P.call(this,["devsite-tabs"])||this;a.b=new X;a.c=!1;a.g=new yb;a.a=null;return a}ha(Z,P);Z.prototype.connectedCallback=function(){zb(this);this.getAttribute("scope")||this.setAttribute("scope","auto");this.c||Ab(this);Bb(this)};Z.prototype.disconnectedCallback=function(){vb(this.b)};
Z.prototype.attributeChangedCallback=function(a,b,c){var d=this,e=[],f=Array.from(this.children);f.forEach(function(h){h.matches('section[tab="'+c+'"]')?e.push(h):h.matches("devsite-tabs")&&(h=h.querySelector('tab[tab="'+c+'"]'))&&e.push(h)});"active"===a&&c&&(e.length?(f.forEach(function(h){h.matches("section[tab][active]")?h.removeAttribute("active"):h.matches("devsite-tabs")&&(h=h.querySelector("tab[tab][active]"))&&(h.removeAttribute("active"),h.setAttribute("aria-selected","false"))}),e.forEach(function(h){h.setAttribute("active",
"");h.matches("tab")&&h.setAttribute("aria-selected","true");Array.from(h.querySelectorAll("iframe[data-src]")).forEach(function(p){p.setAttribute("src",p.getAttribute("data-src"));p.removeAttribute("data-src")})})):this.setAttribute(a,b));if("tab-to-select"===a&&c){if(e.length)this.setAttribute("active",c);else{var g=this.getAttribute("active");f.forEach(function(h){h.matches("devsite-tabs")&&(h=h.querySelector('tab[tab="'+g+'"]'))&&d.setAttribute("active",h.getAttribute("tab"))})}this.removeAttribute("tab-to-select")}};
function Cb(a,b){var c=a.getBoundingClientRect();a.dispatchEvent(new CustomEvent("devsite-sticky-freeze",{bubbles:!0}));var d=a.getAttribute("scope");Array.from(a.ownerDocument.querySelectorAll('devsite-selector[scope="'+d+'"]:not([active="'+(b+'"])'))).forEach(function(g){g!==a&&g.setAttribute("tab-to-select",b)});a.setAttribute("active",b);var e=a.getBoundingClientRect();window.scrollTo(Ka().a,Ka().b+e.top-c.top);a.g.set("pref_ds_"+d,b);var f;Array.from(a.children).forEach(function(g){!f&&g.matches("devsite-tabs")&&
(f=g.querySelector('[tab="'+b+'"]'))});f&&f.id&&Oa("#"+f.id);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))}function Bb(a){a.a&&sb(a.b,a.a,function(b){if(!b.A){b.j();b.s();document.body.dispatchEvent(new CustomEvent("devsite-close-overflow-tabs"));b=b.target;for(var c;!c&&b!==a;)"TAB"===b.tagName.toUpperCase()&&(c=b),b=b.parentNode;c&&Cb(a,c.getAttribute("tab"))}})}
function Ab(a){a.c=!0;var b=a.getAttribute("scope");b=a.g.get("pref_ds_"+b);var c=a.ownerDocument.createElement("devsite-tabs");c.setAttribute("role","tablist");a.hasAttribute("no-overflow")&&c.setAttribute("no-overflow","");a.a=c;Array.from(a.children).filter(function(g){return g.matches("section")}).forEach(function(g){var h=a.ownerDocument.createElement("tab"),p=a.ownerDocument.createElement("a");g.querySelector(".two-line-tab")&&h.setAttribute("two-line","");h.setAttribute("role","tab");h.setAttribute("aria-selected",
"false");var q=g.querySelector("h1,h2,h3,h4,h5,h6"),l="";if(q&&q.innerText.trim()){l="";if(q.id)var Ua=q.id;var y=q.querySelector(".firebase-platform-label");y&&(l=y.textContent,M(y));y=q.innerText;var G=q.childNodes[0],Va=g.querySelector("[tab-label]");Va&&(l=Va.getAttribute("tab-label"));M(q);l?(G=a.ownerDocument.createElement("span"),G.setAttribute("tab-label",l),G.textContent=y.trim(),p.appendChild(G),l=Pa(y+" "+l)):(p.appendChild(G),l=Pa(y)||"tab");h.setAttribute("aria-controls","tabpanel-"+
l);p.id="aria-tab-"+l;p.setAttribute("role","button");q.hasAttributes()&&Array.from(q.attributes).forEach(function(oa){oa.name.startsWith("track-")&&p.setAttribute(oa.name,oa.value)})}else p.textContent="Error",l=Pa("Error");xa(p,"#"+l);h.appendChild(p);c.querySelector('[tab="'+l+'"]')||(h.setAttribute("tab",l),Ua&&(h.id=Ua),c.appendChild(h));g.setAttribute("tab",l);g.setAttribute("role","tabpanel");g.setAttribute("aria-labelledby","aria-tab-"+l);g.setAttribute("tabindex","0");g.id="tabpanel-"+l});
a.insertBefore(c,a.childNodes[0]||null);var d=(new URL(document.location.toString())).hash.substring(1),e=Array.from(a.children),f=c.querySelector('tab[id="'+d+'"]');(e=e.find(function(g){return g.matches(".selected")}))&&e.classList.remove("selected");d&&f?a.setAttribute("active",f.getAttribute("tab")):b&&c.querySelector('[tab="'+b+'"]')?a.setAttribute("tab-to-select",b):e?a.setAttribute("active",e.getAttribute("tab")):a.hasAttribute("active")||a.setAttribute("active",c.querySelector("[tab]").getAttribute("tab"));
a.setAttribute("ready","")}
function zb(a){Array.from(a.children).forEach(function(b){if(b.matches(".ds-selector-tabs,.ds-selector-dropdown,.code-sample,.data-sample")){var c=b.getAttribute("data-ds-scope");c&&a.setAttribute("scope",c);var d=".ds-selector-tabs,.ds-selector-dropdown,.code-sample,.data-sample".split(/[,.]/).filter(function(e){return e.length});Array.from(b.classList).forEach(function(e){d.includes(e)||a.classList.add(e)});for(b.hasAttribute("no-overflow")&&a.setAttribute("no-overflow","");b.childNodes.length;)a.appendChild(b.childNodes[0]);
M(b)}});Array.from(a.children).forEach(function(b){b.matches(".kd-tabbed-horz,.kd-tabbed-vert")&&Db(a,b)})}
function Db(a,b){Array.from(b.children).forEach(function(c){if(c.matches("article")){var d=a.ownerDocument.createElement("section");for(c.classList.contains("selected")&&d.classList.add("selected");c.childNodes.length;)d.appendChild(c.childNodes[0]);var e=d.querySelector("header");if(e){var f=a.ownerDocument.createElement("h3");e.childNodes.length&&f.appendChild(e.childNodes[0]);f.id=e.id;var g=e.parentNode;g&&g.replaceChild(f,e)}a.appendChild(d);M(c)}});M(b)}
da.Object.defineProperties(Z,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["active","tab-to-select"]}}});Z.prototype.attributeChangedCallback=Z.prototype.attributeChangedCallback;Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-selector",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteSelector",a)};}).call(this);
