(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function l(a,b){if(b){var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}var m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var ea={L:!0},fa={};try{fa.__proto__=ea;n=fa.L;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var p=m;
function ha(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(p)p(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.s=b.prototype}l("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var h=d[f];if(b.call(c,h,f,d)){b=h;break a}}b=void 0}return b}});
l("Object.setPrototypeOf",function(a){return a||p});var ia=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=aa(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();
l("Reflect.construct",function(){return ia});l("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var h=0;!(f=b.next()).done;)e.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)e.push(c.call(d,b[h],h));return e}});var q=this||self;function r(){}
function t(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function u(a){var b=t(a);return"array"==b||"object"==b&&"number"==typeof a.length}function v(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ja(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}
function ka(a,b){function c(){}c.prototype=b.prototype;a.s=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.$=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var la;var ma=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},na=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},oa=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};function pa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function qa(a,b){if(!u(a)||!u(b)||a.length!=b.length)return!1;for(var c=a.length,d=ra,e=0;e<c;e++)if(!d(a[e],b[e]))return!1;return!0}function ra(a,b){return a===b}
function sa(a){for(var b=Math.random,c=a.length-1;0<c;c--){var d=Math.floor(b()*(c+1)),e=a[c];a[c]=a[d];a[d]=e}};var ta=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function ua(a,b){if(b)a=a.replace(va,"&amp;").replace(wa,"&lt;").replace(xa,"&gt;").replace(ya,"&quot;").replace(za,"&#39;").replace(Aa,"&#0;");else{if(!Ba.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(va,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(wa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(xa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ya,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(za,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Aa,"&#0;"))}return a}
var va=/&/g,wa=/</g,xa=/>/g,ya=/"/g,za=/'/g,Aa=/\x00/g,Ba=/[\x00&<>"']/;function Ca(a,b){return a<b?-1:a>b?1:0};var w;a:{var Da=q.navigator;if(Da){var Ea=Da.userAgent;if(Ea){w=Ea;break a}}w=""};function Fa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ga(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}var Ha="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ia(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ha.length;f++)c=Ha[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function x(a){this.b=Ja===Ja&&a||"";this.c=Ka}x.prototype.D=!0;x.prototype.C=function(){return this.b.toString()};x.prototype.H=!0;x.prototype.a=function(){return 1};var Ka={},Ja={};function y(){this.b="";this.f=La;this.c=null}y.prototype.H=!0;y.prototype.a=function(){return this.c};y.prototype.D=!0;y.prototype.C=function(){return this.b.toString()};function z(a){return a instanceof y&&a.constructor===y&&a.f===La?a.b:"type_error:SafeHtml"}function A(a){if(a instanceof y)return a;var b="object"==typeof a,c=null;b&&a.H&&(c=a.a());return Ma(ua(b&&a.D?a.C():String(a)),c)}
function Na(a){function b(f){Array.isArray(f)?na(f,b):(f=A(f),e.push(z(f).toString()),f=f.a(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=A(Oa),d=c.a(),e=[];na(a,b);return Ma(e.join(z(c).toString()),d)}function Pa(a){return Na(Array.prototype.slice.call(arguments))}var La={};function Ma(a,b){return Qa(a,b)}function Qa(a,b){var c=new y;c.b=a;c.c=b;return c}var Ra=new y;Ra.b=q.trustedTypes&&q.trustedTypes.emptyHTML?q.trustedTypes.emptyHTML:"";Ra.c=0;var Oa=Ra,Sa=Qa("<br>",0);var Ta=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=z(Oa);return!b.parentElement});function Ua(a,b){if(Ta())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=z(b)};function Va(a){return a=ua(a,void 0)};function Wa(a){Wa[" "](a);return a}Wa[" "]=r;function Xa(a,b){var c=Ya;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Za=-1!=w.indexOf("Opera"),B=-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE"),$a=-1!=w.indexOf("Edge"),C=-1!=w.indexOf("Gecko")&&!(-1!=w.toLowerCase().indexOf("webkit")&&-1==w.indexOf("Edge"))&&!(-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE"))&&-1==w.indexOf("Edge"),D=-1!=w.toLowerCase().indexOf("webkit")&&-1==w.indexOf("Edge"),ab=-1!=w.indexOf("Macintosh");function bb(){var a=q.document;return a?a.documentMode:void 0}var cb;
a:{var db="",eb=function(){var a=w;if(C)return/rv:([^\);]+)(\)|;)/.exec(a);if($a)return/Edge\/([\d\.]+)/.exec(a);if(B)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(D)return/WebKit\/(\S+)/.exec(a);if(Za)return/(?:Version)[ \/]?(\S+)/.exec(a)}();eb&&(db=eb?eb[1]:"");if(B){var fb=bb();if(null!=fb&&fb>parseFloat(db)){cb=String(fb);break a}}cb=db}var gb=cb,Ya={};
function E(a){return Xa(a,function(){for(var b=0,c=ta(String(gb)).split("."),d=ta(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=Ca(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||Ca(0==h[2].length,0==k[2].length)||Ca(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var hb;
if(q.document&&B){var ib=bb();hb=ib?ib:parseInt(gb,10)||void 0}else hb=void 0;var F=hb;var jb=!B||9<=Number(F),kb=!B||9<=Number(F),lb=B&&!E("9"),mb=function(){if(!q.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{q.addEventListener("test",r,b),q.removeEventListener("test",r,b)}catch(c){}return a}();function G(){this.g=this.g;this.b=this.b}g=G.prototype;g.g=!1;g.S=function(){return this.g};g.oa=G.prototype.S;g.G=function(){this.g||(this.g=!0,this.A())};g.zb=function(a){a=ja(nb,a);this.g?a():(this.b||(this.b=[]),this.b.push(a))};g.A=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function nb(a){a&&"function"==typeof a.G&&a.G()};function H(a,b){this.type=a;this.b=this.target=b;this.J=this.f=!1}H.prototype.h=function(){this.f=!0};H.prototype.c=function(){this.J=!0};function I(a,b){H.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.o=this.m=0;this.key="";this.j=this.l=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.I=null;this.K=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(C){a:{try{Wa(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.m=D||void 0!==a.offsetX?a.offsetX:a.layerX,this.o=D||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.l=a.keyCode||0;this.key=a.key||"";this.j=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.K=ab?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:ob[a.pointerType]||"";this.I=a.state;this.a=a;a.defaultPrevented&&this.c()}}ka(I,H);var pb=[1,4,2],ob={2:"touch",3:"pen",4:"mouse"};
I.prototype.W=function(){return(jb?0==this.a.button:"click"==this.type?!0:!!(this.a.button&pb[0]))&&!(D&&ab&&this.ctrlKey)};I.prototype.h=function(){I.s.h.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};I.prototype.c=function(){I.s.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,lb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};I.prototype.V=function(){return this.a};var J="closure_listenable_"+(1E6*Math.random()|0),qb=0;function rb(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++qb;this.i=this.u=!1}function K(a){a.i=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function sb(a){this.src=a;this.a={};this.b=0}g=sb.prototype;g.ab=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};g.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=tb(a,b,d,e);-1<h?(b=a[h],c||(b.u=!1)):(b=new rb(b,this.src,f,!!d,e),b.u=c,a.push(b));return b};
g.cb=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=tb(e,b,c,d);return-1<b?(K(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};g.eb=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,K(d[e]);delete this.a[c];this.b--}return b};g.Ba=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
g.bb=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Ga(this.a,function(f){for(var h=0;h<f.length;++h)if(!(c&&f[h].type!=d||e&&f[h].capture!=b))return!0;return!1})};function tb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.i&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var ub="closure_lm_"+(1E6*Math.random()|0),vb={},wb=0;function xb(a,b,c,d,e){if(d&&d.once)return yb(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)xb(a,b[f],c,d,e);return null}c=zb(c);return a&&a[J]?L(a,b,c,v(d)?!!d.capture:!!d,e):Ab(a,b,c,!1,d,e)}
function Ab(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=v(e)?!!e.capture:!!e,k=M(a);k||(a[ub]=k=new sb(a));c=k.add(b,c,d,h,f);if(c.a)return c;d=Bb();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)mb||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Cb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");wb++;return c}
function Bb(){var a=Db,b=kb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function yb(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)yb(a,b[f],c,d,e);return null}c=zb(c);return a&&a[J]?a.K(b,c,v(d)?!!d.capture:!!d,e):Ab(a,b,c,!0,d,e)}
function Eb(a){if("number"!==typeof a&&a&&!a.i){var b=a.src;if(b&&b[J])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Cb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);wb--;if(c=M(b)){d=a.type;if(d in c.a){var e=c.a[d],f=ma(e,a),h;(h=0<=f)&&Array.prototype.splice.call(e,f,1);h&&(K(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[ub]=null)}else K(a)}}}
function Cb(a){return a in vb?vb[a]:vb[a]="on"+a}function Fb(a,b,c,d){var e=!0;if(a=M(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.i&&(f=Gb(f,d),e=e&&!1!==f)}return e}function Gb(a,b){var c=a.listener,d=a.b||a.src;a.u&&Eb(a);return c.call(d,b)}
function Db(a,b){if(a.i)return!0;if(!kb){if(!b)a:{b=["window","event"];for(var c=q,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new I(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.f&&0<=e;e--){b.b=d[e];var f=Fb(d[e],a,!0,b);c=c&&f}for(e=0;!b.f&&e<d.length;e++)b.b=d[e],f=Fb(d[e],a,!1,b),c=
c&&f}return c}return Gb(a,new I(b,this))}function M(a){a=a[ub];return a instanceof sb?a:null}var Hb="__closure_events_fn_"+(1E9*Math.random()>>>0);function zb(a){if("function"==t(a))return a;a[Hb]||(a[Hb]=function(b){return a.handleEvent(b)});return a[Hb]};var Ib={},Jb={};function N(){throw Error("Do not instantiate directly");}N.prototype.v=null;N.prototype.b=function(){return this.a};N.prototype.toString=function(){return this.a};N.prototype.c=function(){if(this.w!==Jb)throw Error("Sanitized content was not of kind URI.");return new x(this.toString())};function Kb(){N.call(this)}ka(Kb,N);Kb.prototype.w=Ib;function Nb(a){if(null!=a)switch(a.v){case 1:return 1;case -1:return-1;case 0:return 0}return null}function Ob(a){return null!=a&&a.w===Ib?a:a instanceof y?Pb(z(a).toString(),a.a()):Pb(Va(String(String(a))),Nb(a))}var Pb=function(a){function b(c){this.a=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.v=d);return c}}(Kb);var Qb=!B||9<=Number(F),Rb=!C&&!B||B&&9<=Number(F)||C&&E("1.9.1"),Sb=B&&!E("9"),Tb=B||Za||D;function O(a,b){this.a=void 0!==a?a:0;this.b=void 0!==b?b:0}g=O.prototype;g.fb=function(){return new O(this.a,this.b)};g.ca=function(a){return a instanceof O&&(this==a?!0:this&&a?this.a==a.a&&this.b==a.b:!1)};g.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);return this};g.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);return this};g.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);return this};
g.hb=function(a,b){a instanceof O?(this.a+=a.a,this.b+=a.b):(this.a+=Number(a),"number"===typeof b&&(this.b+=b));return this};g.gb=function(a,b){this.a*=a;this.b*="number"===typeof b?b:a;return this};g.Cb=function(a,b){a=a*Math.PI/180;b=b||new O(0,0);var c=this.a,d=this.b,e=Math.cos(a);a=Math.sin(a);this.a=(c-b.a)*e-(d-b.b)*a+b.a;this.b=(c-b.a)*a+(d-b.b)*e+b.b};function Ub(a,b){this.width=a;this.height=b}g=Ub.prototype;g.ib=function(){return new Ub(this.width,this.height)};g.Ca=function(){return Math.max(this.width,this.height)};g.Pa=function(){return Math.min(this.width,this.height)};g.yb=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.ob=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.ga=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Vb(a,b){a.width*=b;a.height*=b;return a}g.Eb=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Vb(this,a)};
g.Fb=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Vb(this,a)};function Wb(a){return a?new P(Q(a)):la||(la=new P)}function Xb(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Yb(document,"*",a,b);return d||null}
function Zb(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,h;h=b[f];f++)e==h.nodeName&&(a[d++]=h);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;h=b[f];f++){e=h.className;var k;if(k="function"==typeof e.split)k=0<=ma(e.split(/\s+/),c);k&&(a[d++]=h)}a.length=d;return a}return b}
function Yb(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):Zb(a,b,c,d)[0]||null}function $b(a,b){Fa(b,function(c,d){c&&"object"==typeof c&&c.D&&(c=c.C());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:ac.hasOwnProperty(d)?a.setAttribute(ac[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var ac={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function bc(a){a=a.document;a=R(a)?a.documentElement:a.body;return new Ub(a.clientWidth,a.clientHeight)}function cc(a){return a.scrollingElement?a.scrollingElement:!D&&R(a)?a.documentElement:a.body||a.documentElement}
function S(a){return a.parentWindow||a.defaultView}function dc(a,b,c,d){function e(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];u(f)&&!ec(f)?na(fc(f)?pa(f):f,e):e(f)}}function T(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function R(a){return"CSS1Compat"==a.compatMode}function gc(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function U(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function V(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function ec(a){return v(a)&&0<a.nodeType}function hc(a){return v(a)&&1==a.nodeType}function ic(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function jc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return kc(b,a)}function kc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function Q(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function lc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else gc(a),a.appendChild(Q(a).createTextNode(String(b)))}function mc(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||mc(a,b,c,d))return!0;a=a.nextSibling}return!1}var nc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},W={IMG:" ",BR:"\n"};
function oc(a){return pc(a)&&qc(a)}function pc(a){return B&&!E("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function qc(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function rc(a){if(Sb&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];sc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Sb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function sc(a,b,c){if(!(a.nodeName in nc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in W)b.push(W[a.nodeName]);else for(a=a.firstChild;a;)sc(a,b,c),a=a.nextSibling}function fc(a){if(a&&"number"==typeof a.length){if(v(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==t(a))return"function"==typeof a.item}return!1}
function tc(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return uc(a,function(f){var h;(h=!e||f.nodeName==e)&&!(h=!c)&&(h="string"===typeof f.className)&&(h=0<=ma(f.className.split(/\s+/),c));return h},!0,d)}function vc(a,b,c){return tc(a,null,b,c)}function uc(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function P(a){this.a=a||q.document||document}g=P.prototype;g.ta=Wb;g.Gb=function(a){this.a=a};g.pa=function(){return this.a};
g.O=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.Na=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.X=P.prototype.O;g.Wa=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.P=function(a,b,c){return Zb(this.a,a,b,c)};g.va=function(a,b,c){return Yb(this.a,a,b,c)};g.wa=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Zb(document,"*",a,b)};g.ua=function(a,b){return Xb(a,b||this.a)};
g.Oa=function(a,b){return Xb(a,b||this.a)};g.Y=P.prototype.P;g.Ib=$b;g.Ra=function(a){return bc(a||S(this.a)||window)};g.qa=function(){var a=S(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=bc(a).height,R(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.N=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!Qb&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',Va(h.name),'"');if(h.type){f.push(' type="',Va(h.type),'"');var k={};Ia(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=T(d,f);h&&("string"===typeof h?f.className=h:Array.isArray(h)?f.className=h.join(" "):$b(f,h));2<e.length&&dc(d,f,e,2);return f};g.Z=P.prototype.N;g.Va=function(a){return this.a.createTextNode(String(a))};
g.ba=function(a,b,c){var d=this.a;c=!!c;for(var e=T(d,"TABLE"),f=e.appendChild(T(d,"TBODY")),h=0;h<a;h++){for(var k=T(d,"TR"),Lb=0;Lb<b;Lb++){var Mb=T(d,"TD");c&&lc(Mb,"\u00a0");k.appendChild(Mb)}f.appendChild(k)}return e};g.Db=function(a){var b=this.a;var c=T(b,"DIV");B?(a=Pa(Sa,a),Ua(c,a),c.removeChild(c.firstChild)):Ua(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.mb=function(){return R(this.a)};
g.sa=function(){return cc(this.a)};g.ra=function(){var a=this.a,b=cc(a);a=S(a);return B&&E("10")&&a.pageYOffset!=b.scrollTop?new O(b.scrollLeft,b.scrollTop):new O(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};g.ia=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.appendChild=function(a,b){a.appendChild(b)};g.Sa=function(a,b){dc(Q(a),a,arguments,1)};g.Ta=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.Bb=gc;g.lb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.kb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.jb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.Xa=U;g.Ya=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.ha=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return U(a)}};
g.na=function(a){return Rb&&void 0!=a.children?a.children:oa(a.childNodes,function(b){return 1==b.nodeType})};g.xa=function(a){return void 0!==a.firstElementChild?a.firstElementChild:V(a.firstChild,!0)};g.Aa=function(a){return void 0!==a.lastElementChild?a.lastElementChild:V(a.lastChild,!1)};g.Da=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:V(a.nextSibling,!0)};g.La=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:V(a.previousSibling,!1)};
g.Ea=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.Ma=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.rb=ec;g.nb=hc;g.tb=function(a){return v(a)&&a.window==a};g.Ka=function(a){var b;if(Tb&&!(B&&E("9")&&!E("10")&&q.SVGElement&&a instanceof q.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return hc(b)?b:null};
g.Ua=ic;
g.aa=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(B&&!(9<=Number(F))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?kc(a,b):!c&&ic(e,b)?-1*jc(a,b):!d&&ic(f,a)?jc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=Q(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(q.Range.START_TO_END,a)};g.da=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){h=d[0][b];for(var k=1;k<c;k++)if(h!=d[k][b])return f;f=h}return f};g.Ja=Q;g.ya=function(a){return a.contentDocument||a.contentWindow.document};
g.za=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?S(c):window}else d=null;b=d}return b}catch(e){}return null};g.Jb=lc;g.Ia=function(a){if("outerHTML"in a)return a.outerHTML;var b=T(Q(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.ea=function(a,b){var c=[];return mc(a,b,c,!0)?c[0]:void 0};g.fa=function(a,b){var c=[];mc(a,b,c,!1);return c};g.qb=oc;g.Hb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.pb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!pc(a)||qc(a)):oc(a))&&B){var c;"function"!=t(a.getBoundingClientRect)||B&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.Qa=rc;g.Ga=function(a){return rc(a).length};
g.Ha=function(a,b){b=b||Q(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(rc(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.Fa=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in nc))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in W)d+=W[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);v(c)&&(c.Ab=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.sb=fc;g.la=tc;g.ka=vc;g.ja=uc;g.ma=function(a){return a.getContext("2d")};function wc(a){var b=a||xc;var c=b.T,d=b.U;a='<div class="devsite-multiple-choice-explanation-correctness">';b.M?1==d?a+="Correct answer.":(b=Ob(c)+(" of "+(Ob(d)+" correct answers.")),a+=b):a+="Try again.";b=Pb(a+"</div>");a=Wb();a=T(a.a,"DIV");if(v(b))if(b instanceof N){if(b.w!==Ib)throw Error("Sanitized content was not of kind HTML.");b=Qa(b.toString(),b.v||null)}else b=A("zSoyz");else b=A(String(b));Ua(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a}var xc={};var yc=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(yc&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function X(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ha(X,HTMLElement);X.prototype.W=function(){console.warn(this.tagName,"has not implemented update")};X.prototype.I=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
X.prototype.V=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function Y(a){G.call(this);this.c=a;this.a={}}ka(Y,G);var zc=[];function Ac(a,b,c){L(a,b,"click",c,void 0)}g=Y.prototype;g.vb=function(a,b,c,d,e){return L(this,a,b,c,d,e)};function L(a,b,c,d,e,f){Array.isArray(c)||(c&&(zc[0]=c.toString()),c=zc);for(var h=0;h<c.length;h++){var k=xb(b,c[h],d||a.handleEvent,e||!1,f||a.c||a);if(!k)break;a.a[k.key]=k}return a}g.$a=function(a,b,c,d){return Bc(this,a,b,c,d)};g.ub=function(a,b,c,d,e){return Bc(this,a,b,c,d,e)};
function Bc(a,b,c,d,e,f){if(Array.isArray(c))for(var h=0;h<c.length;h++)Bc(a,b,c[h],d,e,f);else{b=yb(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}g.wb=function(a,b,c,d){L(b,a,c,d,this.c||this);return this};g.xb=function(a,b,c,d,e){L(b,a,c,d,e||this.c||this);return this};g.Za=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function Cc(a,b,c,d,e,f){if(Array.isArray(c))for(var h=0;h<c.length;h++)Cc(a,b,c[h],d,e,f);else d=d||a.handleEvent,e=v(e)?!!e.capture:!!e,f=f||a.c||a,d=zb(d),e=!!e,b&&b[J]?c=b.J(c,d,e,f):b?(b=M(b))?(c=b.a[c.toString()],b=-1,c&&(b=tb(c,d,e,f)),c=-1<b?c[b]:null):c=null:c=null,c&&(Eb(c),delete a.a[c.key])}g.Kb=function(a,b,c,d,e){Cc(b,a,c,d,e||this.c||this,this);return this};function Dc(a){Fa(a.a,function(b,c){this.a.hasOwnProperty(c)&&Eb(b)},a);a.a={}}g.A=function(){Y.s.A.call(this);Dc(this)};
g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Z(){var a=X.call(this)||this;a.j=new Y;a.m=!1;a.b=null;a.a=[];a.c=[];a.h=0;a.f=0;a.o=!0;a.l=0;return a}ha(Z,X);Z.prototype.connectedCallback=function(){if(!this.m){var a=this.querySelector(".devsite-multiple-choice");if(a){a.hasAttribute("data-preserve-order")&&this.setAttribute("preserve-order","");if(0<a.childNodes.length)for(;a.childNodes.length;)this.appendChild(a.childNodes[0]);U(a)}Ec(this);this.m=!0}Fc(this)};Z.prototype.disconnectedCallback=function(){Dc(this.j)};
function Fc(a){Ac(a.j,a,function(b){Gc(a,b)})}
function Ec(a){a.hasAttribute("preserve-order")&&(a.o=!1,a.removeAttribute("preserve-order"));Array.from(a.children).forEach(function(b,c){if(0===c)b.classList.add("devsite-multiple-choice-question"),a.b=b;else{var d=b.children[0],e=b.children[1];d&&d.classList.add("devsite-multiple-choice-option");e&&(e.classList.add("devsite-multiple-choice-explanation"),e.style.display="none");var f=!1;if(b.hasAttribute("data-correct")||b.hasAttribute("correct"))a.h++,f=!0,b.hasAttribute("data-correct")&&b.removeAttribute("data-correct"),
b.hasAttribute("correct")&&b.removeAttribute("correct");a.a.push({id:c,F:d,B:e,R:f});U(b)}});a.o&&sa(a.a);a.a.forEach(function(b){if(b.F&&b.B){var c=document.createElement("div");c.classList.add("devsite-multiple-choice-answer");c.setAttribute("answer-id",b.id);c.setAttribute("tabindex","0");c.setAttribute("role","button");c.appendChild(b.F);c.appendChild(b.B);a.appendChild(c)}});a.setAttribute("ready","")}
function Gc(a,b){var c=vc(b.target,"devsite-multiple-choice-answer");if(!c||!c.hasAttribute("clicked")){c.setAttribute("clicked","");var d=parseInt(c.getAttribute("answer-id"),10);a.c.push(d);var e=a.a.find(function(h){return h.id===d});b=e.F;var f=e.B;e=e.R;Hc(a,e);e&&a.f++;c.setAttribute(e?"correct":"incorrect","");f&&(c=wc({M:e,T:a.f,U:a.h}),f.appendChild(c),f.style.display="block");b&&Ic(a,b,""+e)}}
function Hc(a,b){b=new CustomEvent("devsite-multiple-choice-answer-selected",{detail:{"is-correct":b},bubbles:!0});a.dispatchEvent(b)}
function Ic(a,b,c){var d=a.c.length;1===d&&(a.l=Date.now(),b={action:a.b.innerText,category:"MCE First Selection",label:b.innerText,value:c},a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:b,bubbles:!0})));d===a.a.length&&(d=a.a.map(function(e){return e.id}),b={action:qa(d,a.c)?"Selected sequentially":"Selected out of order",category:"MCE All Selected",label:a.b.innerText,value:""+Math.floor((Date.now()-a.l)/1E3)},a.dispatchEvent(new CustomEvent("devsite-analytics-observation",
{detail:b,bubbles:!0})))}Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-multiple-choice",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteMultipleChoice",a)};}).call(this);
